import { DirMenuManagementData } from "../directory-menu-management/hook/CompProvider";

interface exclusivePortalMgrData {
  seq: number;
  portalId: number;
}

export interface PortalMgrData
  extends DirMenuManagementData,
    exclusivePortalMgrData {}

export const mockPortalMgrData: PortalMgrData[] = [
  {
    seq: 1783,
    portalId: 1041,
    id: 111000,
    type: "0",
    name: "Billing Center Portal",
    hasChildren: true,
  },
  {
    url: "vc/modules/vc-config/modules/license/views/LicenseView",
    seq: 1784,
    portalId: 1041,
    id: 1204,
    parentId: 111000,
    type: "1",
    name: "VC License View",
    hasChildren: true,
  },
  {
    seq: 1785,
    portalId: 1041,
    id: 99,
    type: "0",
    name: "IT Center Administrator Portal",
    hasChildren: true,
  },
  {
    seq: 1786,
    portalId: 1041,
    id: 5,
    parentId: 99,
    type: "0",
    name: "Bulletin Management collection",
    hasChildren: true,
  },
  {
    url: "modules/bulletinmgr/views/BulletinMgr",
    seq: 1787,
    portalId: 1041,
    id: 29,
    parentId: 5,
    type: "1",
    name: "Bulletin Management",
    hasChildren: true,
  },
  {
    url: "modules/bulletinconfig/views/BulletinConfigMgr",
    seq: 1788,
    portalId: 1041,
    id: 30,
    parentId: 5,
    type: "1",
    name: "BulletinConfig Management",
    hasChildren: true,
  },
  {
    seq: 1789,
    portalId: 1041,
    id: 2,
    parentId: 99,
    type: "0",
    name: "Privilege Management",
    hasChildren: true,
  },
  {
    url: "modules/dirmenumgr/views/DirMenuMgr",
    seq: 1790,
    portalId: 1041,
    id: 8,
    parentId: 2,
    type: "1",
    name: "Directory Menu Management",
    hasChildren: true,
  },
  {
    url: "modules/componentmgr/views/ComponentMgr",
    seq: 1791,
    portalId: 1041,
    id: 9,
    parentId: 2,
    type: "1",
    name: "Component Management",
    hasChildren: true,
  },
  {
    url: "modules/portalmgr/views/PortalMgr",
    seq: 1792,
    portalId: 1041,
    id: 10,
    parentId: 2,
    type: "1",
    name: "Portal Management",
    hasChildren: true,
  },
  {
    url: "modules/portletmgr/views/PortletMgr",
    seq: 1793,
    portalId: 1041,
    id: 11,
    parentId: 2,
    type: "1",
    name: "Portlet Privilege Management",
    hasChildren: true,
  },
  {
    url: "modules/dataprivmgr/views/DataPrivMgrView",
    seq: 1794,
    portalId: 1041,
    id: 12,
    parentId: 2,
    type: "1",
    name: "Data Privilege Management",
    hasChildren: true,
  },
  {
    url: "modules/batchprivmgr/views/BatchPrivMgr",
    seq: 1795,
    portalId: 1041,
    id: 69,
    parentId: 2,
    type: "1",
    name: "Batch Privilege Management",
    hasChildren: true,
  },
  {
    url: "modules/batchprivmgr/views/BatchPrivLog",
    seq: 1796,
    portalId: 1041,
    id: 71,
    parentId: 2,
    type: "1",
    name: "Batch Privilege Log",
    hasChildren: true,
  },
  {
    seq: 1797,
    portalId: 1041,
    id: 3,
    parentId: 99,
    type: "0",
    name: "Staff & Organization Management",
    hasChildren: true,
  },
  {
    url: "modules/areamgr/views/AreaMgr",
    seq: 1798,
    portalId: 1041,
    id: 14,
    parentId: 3,
    type: "1",
    name: "Area Management",
    hasChildren: true,
  },
  {
    url: "modules/stafforg/views/StaffOrgMgr",
    seq: 1799,
    portalId: 1041,
    id: 15,
    parentId: 3,
    type: "1",
    name: "Organization & Staff Management",
    hasChildren: true,
  },
  {
    url: "modules/stafforg/views/OrgTypeMgrView",
    seq: 1800,
    portalId: 1041,
    id: 16,
    parentId: 3,
    type: "1",
    name: "Organization Type Management",
    hasChildren: true,
  },
  {
    url: "modules/featuremgr/views/FeatureMgrView",
    seq: 1801,
    portalId: 1041,
    id: 17,
    parentId: 3,
    type: "1",
    name: "Feature Management",
    hasChildren: true,
  },
  {
    seq: 1802,
    portalId: 1041,
    id: 4,
    parentId: 99,
    type: "0",
    name: "System Management",
    hasChildren: true,
  },
  {
    url: "modules/sysparam/views/SystemParameterMgr",
    seq: 1803,
    portalId: 1041,
    id: 19,
    parentId: 4,
    type: "1",
    name: "System Parameter Management",
    hasChildren: true,
  },
  {
    url: "modules/logmgr/views/LogMgr",
    seq: 1804,
    portalId: 1041,
    id: 20,
    parentId: 4,
    type: "1",
    name: "Log Management",
    hasChildren: true,
  },
  {
    url: "modules/onlineusermgr/views/OnlineUserMgr",
    seq: 1805,
    portalId: 1041,
    id: 21,
    parentId: 4,
    type: "1",
    name: "Online User Management",
    hasChildren: true,
  },
  {
    url: "static/worktime/modules/worktimeMgr/views/WorkTimeMgr",
    seq: 1806,
    portalId: 1041,
    id: 22,
    parentId: 4,
    type: "1",
    name: "Work Time Management",
    hasChildren: true,
  },
  {
    url: "modules/mvnomgr/views/MvnoMgrView.js",
    seq: 1807,
    portalId: 1041,
    id: 23,
    parentId: 4,
    type: "1",
    name: "MVNO Management",
    hasChildren: true,
  },
  {
    url: "i18n/modules/onlinetranslate/views/OnlineTranslate",
    seq: 1808,
    portalId: 1041,
    id: 24,
    parentId: 4,
    type: "1",
    name: "Online Translate",
    hasChildren: true,
  },
  {
    url: "modules/admgr/views/AdMgr",
    seq: 1809,
    portalId: 1041,
    id: 26,
    parentId: 4,
    type: "1",
    name: "AD Management",
    hasChildren: true,
  },
  {
    url: "modules/refreshcache/views/cacheView",
    seq: 1810,
    portalId: 1041,
    id: 27,
    parentId: 4,
    type: "1",
    name: "Cache Refresh",
    hasChildren: true,
  },
  {
    url: "modules/mvnousermgr/views/UserMgr.js",
    seq: 1811,
    portalId: 1041,
    id: 28,
    parentId: 4,
    type: "1",
    name: "MVNO User Management",
    hasChildren: true,
  },
  {
    url: "modules/protocolmgr/views/SysProMgrView",
    seq: 1812,
    portalId: 1041,
    id: 31,
    parentId: 4,
    type: "1",
    name: "T&C Management",
    hasChildren: true,
  },
  {
    url: "modules/stafforg/views/UserGroupView.js",
    seq: 1813,
    portalId: 1041,
    id: 32,
    parentId: 4,
    type: "1",
    name: "User Group Management",
    hasChildren: true,
  },
  {
    url: "modules/dataprivmgr/views/GrantUserDataPriv",
    seq: 1814,
    portalId: 1041,
    id: 46,
    parentId: 4,
    type: "1",
    name: "Grant User Data Privilege",
    hasChildren: true,
  },
  {
    url: "modules/protocolmgr/views/SysProAcceptLog",
    seq: 1815,
    portalId: 1041,
    id: 54,
    parentId: 4,
    type: "1",
    name: "T&C Acceptance Log",
    hasChildren: true,
  },
  {
    url: "modules/infsendqueue/views/InfSendQueueView",
    seq: 1816,
    portalId: 1041,
    id: 58,
    parentId: 4,
    type: "1",
    name: "Inf Send Queue",
    hasChildren: true,
  },
  {
    url: "modules/cache/views/CacheManagementView",
    seq: 1817,
    portalId: 1041,
    id: 59,
    parentId: 4,
    type: "1",
    name: "Cache management",
    hasChildren: true,
  },
  {
    url: "modules/logmgr/views/LogServiceMgr",
    seq: 1818,
    portalId: 1041,
    id: 60,
    parentId: 4,
    type: "1",
    name: "Servlog Rela Management",
    hasChildren: true,
  },
  {
    url: "modules/sysparam/views/PageContentMgr",
    seq: 1819,
    portalId: 1041,
    id: 61,
    parentId: 4,
    type: "1",
    name: "Page Content Management",
    hasChildren: true,
  },
  {
    url: "modules/statistics/views/MenuStatisticView",
    seq: 1820,
    portalId: 1041,
    id: 62,
    parentId: 4,
    type: "1",
    name: "Menu Click Statistic",
    hasChildren: true,
  },
  {
    url: "static/authority/modules/authorityMgr/views/ExceedAuthMgr",
    seq: 1821,
    portalId: 1041,
    id: 68,
    parentId: 4,
    type: "1",
    name: "Vertical Privilege Escalation Management",
    hasChildren: true,
  },
  {
    seq: 1822,
    portalId: 1041,
    id: 1,
    parentId: 99,
    type: "0",
    name: "User & Role Management",
    hasChildren: true,
  },
  {
    url: "modules/rolemgr/views/RoleMgr",
    seq: 1823,
    portalId: 1041,
    id: 6,
    parentId: 1,
    type: "1",
    name: "Role Management",
    hasChildren: true,
  },
  {
    url: "modules/usermgr/views/UserMgr",
    seq: 1824,
    portalId: 1041,
    id: 7,
    parentId: 1,
    type: "1",
    name: "User Management",
    hasChildren: true,
  },
  {
    url: "modules/systemuser/views/SysUserQueryView",
    seq: 1825,
    portalId: 1041,
    id: 50,
    parentId: 1,
    type: "1",
    name: "User Inquiry",
    hasChildren: true,
  },
  {
    url: "cvbs/png/modules/billing/balancemgr/views/BalanceAdjustment",
    seq: 1843,
    portalId: 1041,
    id: 1124,
    parentId: 111000,
    type: "1",
    name: "TCEL Balance Adjustment",
    hasChildren: true,
  },
  {
    url: "vc/modules/card-manage/modules/card-create/views/CardCreateView",
    seq: 1844,
    portalId: 1041,
    id: 135002,
    parentId: 111000,
    type: "1",
    name: "VC Card Generation",
    hasChildren: true,
  },
  {
    url: "vc/modules/card-manage/modules/card-create/views/CardCreateView",
    seq: 1845,
    portalId: 1041,
    id: 1284,
    parentId: 111001,
    type: "1",
    name: "VC Card Generation1",
    hasChildren: true,
  },
  {
    url: "cvbs/modules/offer/views/ProductView",
    seq: 1848,
    portalId: 1041,
    id: 111067,
    parentId: 111000,
    type: "1",
    name: "Offer",
    hasChildren: true,
  },
  {
    url: "cvbs/modules/wholesale/views/WholesaleMonitorView",
    seq: 1849,
    portalId: 1041,
    id: 1285,
    parentId: 111000,
    type: "1",
    name: "Wholesale Monitor",
    hasChildren: true,
  },
  {
    url: "cvbs/png/modules/batch/views/BatchRegisterCustinfoView",
    seq: 1850,
    portalId: 1041,
    id: 1286,
    parentId: 111001,
    type: "1",
    name: "Batch Register Cust info",
    hasChildren: true,
  },
  {
    url: "cvbs/png/modules/batch/views/BatchChangeSubsPlanView",
    seq: 1851,
    portalId: 1041,
    id: 1287,
    parentId: 111000,
    type: "1",
    name: "Batch Change Subs Plan",
    hasChildren: true,
  },
];

const mock = {
  boAccessName: "custOrder",
  commonDataId: "2ghpOtw2IAJbMwRikaXR4QD82ldki7yG",
  dirtyList: [
    {
      action: "OVERRIDE",
      bo: false,
      boAccessName: "custOrder",
      filters: {},
      flushed: false,
      isRoot: "Y",
      location: {
        accessNamePath: "/",
        array: false,
        bo: true,
        dataType: "BO",
        includeObjectId: "2f20e016-f047-4677-abe6-7df4b370f121",
        itemAccessName: "custOrder",
        itemType: "VI",
        parentArray: false,
      },
      value: {
        SERV_TYPE: "15",
        CUST_ID: 1335249,
        CREATED_DATE: "2025-08-13 16:21:06",
        SP_ID: 0,
        ACCEPT_DATE: "2025-08-13 16:21:06",
        CUST_ORDER_ID: 121218913,
        ROUTING_ID: 1,
        OFFER_ID: "4",
        POS_SALE_MODE: 1,
        CONTACT_CHANNEL_ID: 1,
        A_PARTY_CODE: "1335249",
        ORDER_ITEM: [
          {
            SERV_TYPE: 15,
            DP_OFFER_ORDER: [
              {
                SERV_TYPE: 139,
                SP_ID: 0,
                ABS_EFF_DATE: "2024-10-16 16:59:09",
                OFFER_TYPE: "3",
                OFFER_NAME: "Data Service",
                OFFER_ID: 73,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "46cbec13-e33b-4fad-b670-41ec1f9fcf66",
                OLD_EFF_DATE: "2024-10-16 16:59:09",
                OFFER_INST_ID: 121293018,
                ORDER_ITEM_ID: 121176060,
              },
              {
                SERV_TYPE: 386,
                SP_ID: 0,
                ABS_EFF_DATE: "2024-10-16 16:59:09",
                OFFER_TYPE: "3",
                OFFER_NAME: "Incoming SMS",
                OFFER_ID: 74,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "34112ec1-843d-4d08-9036-50ffcf337008",
                OLD_EFF_DATE: "2024-10-16 16:59:09",
                OFFER_INST_ID: 121293019,
                ORDER_ITEM_ID: 121176060,
              },
              {
                SERV_TYPE: 385,
                SP_ID: 0,
                ABS_EFF_DATE: "2024-10-16 16:59:09",
                OFFER_TYPE: "3",
                OFFER_NAME: "Outgoing SMS",
                OFFER_ID: 75,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "90ee5c78-3263-40ea-b8b1-bb7c95be96a8",
                OLD_EFF_DATE: "2024-10-16 16:59:09",
                OFFER_INST_ID: 121293020,
                ORDER_ITEM_ID: 121176060,
              },
              {
                SERV_TYPE: 138,
                SP_ID: 0,
                ABS_EFF_DATE: "2024-10-16 16:59:09",
                OFFER_TYPE: "3",
                OFFER_NAME: "Voice Service",
                OFFER_ID: 72,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "8431640c-bc77-4e63-b244-55199451b6d8",
                OLD_EFF_DATE: "2024-10-16 16:59:09",
                OFFER_INST_ID: 121293021,
                ORDER_ITEM_ID: 121176060,
              },
              {
                SP_ID: 0,
                ABS_EFF_DATE: "2025-06-19 14:08:41",
                OFFER_TYPE: "4",
                OFFER_NAME: "Flagging Voucher Data Testing",
                OFFER_ID: 3901,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "39e8ac41-9081-49b2-81b2-4d93da48fd39",
                OLD_EFF_DATE: "2025-06-19 14:08:41",
                OFFER_INST_ID: 122276010,
                ORDER_ITEM_ID: 121176060,
                DUPLICATE_FLAG: "A",
              },
              {
                SP_ID: 0,
                ABS_EFF_DATE: "2025-05-15 10:49:34",
                OFFER_TYPE: "4",
                OFFER_NAME: "WhiteList Number - Recharge Bonus 11x",
                OFFER_ID: 911,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "48cb4c56-8d11-4bb7-aad3-d2f29de682ae",
                OLD_EFF_DATE: "2025-05-15 10:49:34",
                OFFER_INST_ID: 122273023,
                ORDER_ITEM_ID: 121176060,
              },
              {
                SP_ID: 0,
                ABS_EFF_DATE: "2025-06-25 19:15:57",
                OFFER_TYPE: "4",
                OFFER_NAME: "Local Quota Bundling",
                OLD_AGM_EXP_DATE: "2025-06-25 19:15:57",
                OFFER_ID: 3102,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "dcfbec02-678c-45d1-a143-15241a1ce409",
                AGM_EXP_DATE: "2025-06-25 19:15:57",
                OLD_EFF_DATE: "2025-06-25 19:15:57",
                OFFER_INST_ID: 122277010,
                ORDER_ITEM_ID: 121176060,
                DUPLICATE_FLAG: "B",
              },
              {
                SP_ID: 0,
                ABS_EFF_DATE: "2025-06-11 15:28:32",
                OFFER_TYPE: "4",
                OFFER_NAME: "Flag for Telkomcel Point Redemption",
                OFFER_ID: 603,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "174ab20a-eb2e-4aee-8c20-c1fb6c8e3a8f",
                OLD_EFF_DATE: "2025-06-11 15:28:32",
                OFFER_INST_ID: 122275006,
                ORDER_ITEM_ID: 121176060,
              },
            ],
            ACCT: {
              CUST_ID: 1335249,
              ROUTING_ID: 1,
              ACCT_ID: 1335249,
              STATE: "A",
              BILLING_CYCLE_TYPE_ID: 1,
              DELIVER_METHOD: "",
              PAYMENT_TYPE: "B",
              PARTY_TYPE: "A",
              ACCT_NBR: "73094691",
              POSTPAID: "N",
              PARTY_CODE: "0",
            },
            SUBS_PLAN_NAME: "SC_1000_Prepaid_Reguler",
            CUST_ORDER_ID: 121218913,
            OFFER_ID: 4,
            CONTACT_CHANNEL_ID: 1,
            IS_CHECK_OWE_CHARGE: true,
            SUBS_EVENT_ID: 189,
            ORDER_NBR: "2025081321176060",
            ACCT_ID: 1335249,
            IS_RESERVE: false,
            ORDER_TYPE: "B",
            OPERATION_TYPE: "A",
            SUBS_PLAN_ID: 360,
            CUST_ID: 1335249,
            SP_ID: 0,
            STATE_DATE: "2025-08-13 16:21:06",
            ORDER_STATE: "I",
            POS_SALE_MODE: 1,
            PREFIX: "670",
            IS_SAVED: true,
            POSTPAID: "N",
            PROD_STATE: "A",
            BLOCK_REASON: "00000000000000",
            SUBS_ID: 121293017,
            OFFER_NAME: "Telkomcel Prepaid Channel",
            ACC_NBR: "73094691",
            ORDER_ITEM_ID: 121176060,
            CUST_NAME: "67073094691",
          },
        ],
        CUST: {
          CUST_ID: 1335249,
          BIRTHDAY_DAY: "2024-10-10 00:00:00",
          ROUTING_ID: 1,
          CUST_TYPE: "A",
          CUST_CODE: "11335249",
          CERT_ID: 1335249,
          CUST_NAME: "67073094691",
        },
        SUBS_EVENT_ID: 189,
        CUST_CONTACT: {
          CUST_ID: 1335249,
          CREATED_DATE: "2025-08-13 16:21:06",
          SP_ID: 0,
          PARTY_TYPE: "A",
          CUST_CONTACT_ID: 187455313,
          CONTACT_TYPE: "A",
          CONTACT_CHANNEL_ID: 1,
          RELA_ID: 121218913,
          CONTACT_EVENT_ID: "A",
          PARTY_CODE: "1",
        },
        PARTY_TYPE: "A",
        SEND_PROVISIONING_FLAG: "Y",
        CUST_ORDER_NBR: "121218913",
        CREDIT_LIMIT_MODE: "0",
        A_PARTY_TYPE: "D",
        STAFF_INFO: { AREA_ID: 1, ORG_ID: 1, STAFF_ID: 1, STAFF_JOB_ID: 1 },
        PARTY_CODE: "1",
      },
      valueType: "VI",
    },
  ],
  dsi: {},
  errors: [],
  hints: [],
  rollbackList: [],
  wizardPage: {
    accessName:
      "com.ztesoft.zsmart.bss.fiji.cc.orderentry.products.view.BusinessChange",
    accessPath:
      "fiji/customercare/sharepage/flowpage/orderentry/BusinessChangePage.swf",
    canBackward: false,
    canForward: true,
    code: "BusinessChange",
    id: "BusinessChange",
    properties: {},
  },
};
