interface TcelBalanceAdjustmentList {
  acctId: number;
  custId: number | null;
  acctNbr: string | null;
  acctName: string | null;
  billingCycleTypeId: number | null;
  billFormatId: number | null;
  postpaid: string | null;
  stdAddrId: number | null;
  billAddress: string | null;
  paymentType: string | null;
  paymentMethodId: number | null;
  bankId: number | null;
  bankAcctNbr: string | null;
  bankAcctName: string | null;
  createdDate: string | null;
  updateDate: string | null;
  state: string | null;
  stateDate: string | null;
  billingCycleTypeName: string | null;
  defaultFlag: string | null;
  paymentTypeName: string | null;
  bankName: string | null;
  custName: string | null;
  certNbr: string | null;
  certTypeName: string | null;
  address: string | null;
  isProject: string | null;
  routingId: number | null;
  paymentMethodName: string | null;
  paymentComments: string | null;
  bankCardType: string | null;
  isLock: string | null;
  spId: 0;
  allowModStateDate: string | null;
  custType: string | null;
}
interface TcelBalanceAdjustmentPayload {
  acctId: number;
  custId: number | null;
  acctNbr: string | null;
  acctName: string | null;
  billingCycleTypeId: number | null;
  billFormatId: number | null;
  postpaid: string | null;
  stdAddrId: number | null;
  billAddress: string | null;
  paymentType: string | null;
  paymentMethodId: number | null;
  bankId: number | null;
  bankAcctNbr: string | null;
  bankAcctName: string | null;
  createdDate: string | null;
  updateDate: string | null;
  state: string | null;
  stateDate: string | null;
  billingCycleTypeName: string | null;
  defaultFlag: string | null;
  paymentTypeName: string | null;
  bankName: string | null;
  custName: string | null;
  certNbr: string | null;
  certTypeName: string | null;
  address: string | null;
  isProject: string | null;
  routingId: number | null;
  paymentMethodName: string | null;
  paymentComments: string | null;
  bankCardType: string | null;
  isLock: string | null;
  spId: 0;
  allowModStateDate: string | null;
  custType: string | null;
}

interface FilterExpired {
  acctInfo: {
    acctId: number;
    custId: number;
    acctNbr: string;
    acctName: string | null;
    billingCycleTypeId: number | null;
    billFormatId: number | null;
    postpaid: string | null;
    stdAddrId: number | null;
    billAddress: string | null;
    paymentType: string;
    paymentMethodId: number | null;
    bankId: number | null;
    bankAcctNbr: string | null;
    bankAcctName: string | null;
    createdDate: string;
    updateDate: string;
    state: string;
    stateDate: string;
    billingCycleTypeName: string | null;
    defaultFlag: string | null;
    paymentTypeName: string;
    bankName: string | null;
    custName: string | null;
    certNbr: string | null;
    certTypeName: string | null;
    address: string | null;
    isProject: string | null;
    routingId: number | null;
    paymentMethodName: string | null;
    paymentComments: string | null;
    bankCardType: string | null;
    isLock: string | null;
    spId: 0;
    allowModStateDate: string | null;
    custType: string | null;
  };
  balList: BalList[] | null;
}
interface BalList {
  balAcctItemType: balAcctItemType[] | null;
  acctRes: acctRes | null;
  acctId: number | null;
  acctResId: number | null;
  grossBal: number | null;
  consumeBal: number | null;
  ratingBal: number | null;
  billingBal: number | null;
  effDate: string;
  expDate: string | null;
  updateDate: string;
  ceilLimit: number | null;
  floorLimit: number | null;
  dailyCeilLimit: number | null;
  dailyFloorLimit: number | null;
  priority: number | null;
  initBal: number | null;
  balId: 1000008;
  balUsed: number | null;
  subsId: number | null;
}

interface balAcctItemType {
  balId: number | null;
  acctItemTypeId: number | null;
  spId: number | null;
}

interface acctRes {
  acctResId: number;
  balType: number;
  acctResName: string;
  isCurrency: string;
  parentAcctRestId: number | null;
  comments: string | null;
  creditLimit: number | null;
  remindDay: number | null;
  remindValue: number | null;
  maxValue: number | null;
  refillable: string | null;
  paymentForce: string | null;
  stdCode: string | null;
  isFreeUnit: string | null;
  defaultAcctItemTypeId: number | null;
  spId: number | null;
  unitTypeId: number | null;
  unitPrecision: number | null;
  ratioMoney: number | null;
  ratioPrecision: number | null;
  priority: number | null;
  extendRule: string | null;
  maxExpDate: number | null;
  maxAdjustValue: number | null;
  maxChgValue: number | null;
  resetZero: string | null;
  periodClass: string | null;
  storeUnit: number | null;
  acmType: string | null;
  acmThreshold: number | null;
  acmUnit: string | null;
  acmAmount: number | null;
  acmLimit: number | null;
  floorLimit: number | null;
  dailyCeilLimit: number | null;
  dailyFloorLimit: number | null;
  overdraftFlag: string | null;
  balanceAggregation: string | null;
  rolOverFlag: string | null;
  category: string | null;
  reservePercentage: number | null;
  balCategory: string | null;
  gracePeriod: number | null;
  maxRollOver: number | null;
  usageType: number | null;
  rewardFlag: string | null;
  unlimitedFlag: string | null;
  adjustType: number | null;
  freeFlag: string | null;
  clearFlag: string | null;
  clearDays: number | null;
  customerFlag: string | null;
}

interface AcctInfo {
  acctId: number | null;
  custId: number | null;
  acctNbr: string | null;
  acctName: string | null;
  billingCycleTypeId: number | null;
  billFormatId: number | null;
  postpaid: string | null;
  stdAddrId: number | null;
  billAddress: string | null;
  paymentType: string | null;
  paymentMethodId: number | null;
  bankId: number | null;
  bankAcctNbr: string | null;
  bankAcctName: string | null;
  createdDate: "2023-12-01";
  updateDate: "2023-12-01";
  state: "A";
  stateDate: "2023-12-01";
  billingCycleTypeName: "Prepid BC1";
  defaultFlag: null;
  paymentTypeName: "Manual payment";
  bankName: null;
  custName: "CUG1";
  certNbr: null;
  certTypeName: null;
  address: null;
  isProject: "N";
  routingId: 1;
  paymentMethodName: null;
  paymentComments: null;
  bankCardType: null;
  isLock: null;
  spId: 0;
  allowModStateDate: null;
  custType: "A";
}

interface payQuery {
  accNbr?: number;
  acctNbr?: string;
  custName?: string;
  spId: number;
  page: number;
  size: number;
  sortBy: string;
  sortDirection: "asc" | "desc";
}
