import { SubsDetail } from "@/pages/main-menu/order/models/interfaces";

export const mockDetail: SubsDetail = {
  acctEx: {
    updateDate: "2025/09/26 16:24:58",
    routingId: 1,
    defaultFlag: undefined,
    address: undefined,
    bankAcctName: undefined,
    paymentTypeName: "Automatic payment",
    postpaid: "N",
    acctId: 120255000,
    billingCycleTypeName: "PREPAID",
    spId: 0,
    billingCycleTypeId: 1,
    paymentType: "A",
    bankId: undefined,
    createdDate: "2025/09/26 16:24:58",
    deliverMethod: undefined,
    paymentMethodId: undefined,
    custId: 120265000,
    stateDate: "2025/09/26 16:24:58",
    state: "A",
    billFormatId: undefined,
    bankAcctNbr: undefined,
    acctNbr: 930255000,
    stdAddrId: undefined,
  },
  set: undefined,
  subsUser: {
    updateDate: "2025/09/26 00:00:00",
    certTypeName: "Passport",
    routingId: 1,
    gender: "M",
    impGradeId: undefined,
    cert: {
      effDate: undefined,
      certNbr: 1234567,
      issueCountry: undefined,
      certTypeId: 1,
      operationType: undefined,
      certId: 120011000,
      certAddress: undefined,
      issueDate: undefined,
      spId: 0,
      issueOrg: undefined,
      expDate: undefined,
    },
    thirdName: undefined,
    partyType: "A",
    religionId: 0,
    fourName: undefined,
    industryId: 0,
    occupationId: 0,
    custTitleId: 0,
    custId: 120265000,
    state: "A",
    email: undefined,
    secondName: undefined,
    comments: undefined,
    address: undefined,
    netType: "A",
    certId: 120011000,
    custName: "Development Test",
    spId: undefined,
    custCode: "1120265000",
    parentId: 0,
    zipcode: undefined,
    firstName: undefined,
    areaId: undefined,
    createdDate: "2025/09/26 00:00:00",
    phoneNumber: undefined,
    birthdayDay: undefined,
    partyCode: "1",
    custType: "A",
    custCreditGradeId: 0,
    stateDate: "2025/09/26 00:00:00",
    pwd: "QFfpQMMfO6o=",
    stdAddrId: undefined,
  },
  subsDefpp: undefined,
  subsUppInstExList: [
    {
      subsUppInstId: 122286032,
      updateDate: "2025/09/26 16:28:29",
      routingId: undefined,
      parentOfferId: undefined,
      subsUppInstExList: undefined,
      needUpload: undefined,
      prodId: undefined,
      prodAlias: undefined,
      expDate: undefined,
      offerType: "4",
      effDate: "2025/09/26 16:28:29",
      stateName: undefined,
      paramStartDate: undefined,
      parentSubsUppInstId: undefined,
      uploadType: undefined,
      servType: undefined,
      paramEndDate: undefined,
      state: "A",
      agreementLimit: undefined,
      offerName: "Prepaid_Reguler_DPP",
      priority: undefined,
      pricePlanId: 79,
      spId: undefined,
      completedDate: "2025/09/26 16:28:29",
      pricePlanType: "2",
      subsId: 121308008,
      createdDate: "2025/09/26 16:28:29",
      applyLevel: "S",
      packageFlag: "N",
      agreementTimeUnit: undefined,
      agmEffDate: undefined,
      stateDate: "2025/09/26 16:28:29",
      agmExpDate: undefined,
    },
    {
      subsUppInstId: 122289003,
      updateDate: "2025/10/20 12:21:56",
      routingId: "",
      // parentOfferId: "",
      subsUppInstExList: "",
      needUpload: "",
      // prodId: "",
      prodAlias: "",
      expDate: "2025/10/21 12:12:47",
      offerType: "4",
      effDate: "2025/10/20 12:21:56",
      stateName: "",
      paramStartDate: "",
      // parentSubsUppInstId: "",
      uploadType: "",
      servType: "",
      paramEndDate: "",
      state: "A",
      // agreementLimit: "",
      offerName: "RAPIDO Socmed 75MB",
      priority: "",
      pricePlanId: 172,
      spId: "",
      completedDate: "2025/10/20 12:21:56",
      pricePlanType: "3",
      subsId: 121308008,
      createdDate: "2025/10/20 12:21:56",
      applyLevel: "S",
      packageFlag: "N",
      agreementTimeUnit: "",
      agmEffDate: "",
      stateDate: "2025/10/20 12:21:56",
      subsUppInstValueExList: [
        {
          subsUppInstId: 122289003,
          updateDate: "",
          // routingId: "",
          attrCode: "TECL_AUTO_RENEW_STATUS",
          needUpload: "",
          spId: 0,
          expDate: "",
          attrType: "1",
          effDate: "2025/10/20 12:21:56",
          createdDate: "",
          attrId: 400004,
          uploadType: "",
          inputType: "1",
          value: "AR Inactive",
          attrName: "Auto Renew Status",
          createDate: "",
        },
      ],
      agmExpDate: "",
    },
  ],
  subsPlan: {
    subsPlanId: 360,
    eligibleFlag: undefined,
    subsPlanName: undefined,
    effDate: undefined,
    isBundleFlag: "N",
    subsPlanCode: undefined,
    saleFlag: "0",
    priority: "1",
    spId: 0,
    expDate: undefined,
    indepProdSpecId: 4,
  },
  subsPlanVer: {
    effDate: "2023/07/01 00:00:00",
    refOfferVerId: undefined,
    offerId: 360,
    state: undefined,
    spId: 0,
    expDate: undefined,
    seq: "1",
    offerVerId: 283,
  },
  subsCust: {
    updateDate: "2025/09/26 00:00:00",
    certTypeName: "Passport",
    routingId: 1,
    gender: "M",
    impGradeId: undefined,
    cert: {
      effDate: undefined,
      certNbr: 1234567,
      issueCountry: undefined,
      certTypeId: 1,
      operationType: undefined,
      certId: 120011000,
      certAddress: undefined,
      issueDate: undefined,
      spId: 0,
      issueOrg: undefined,
      expDate: undefined,
    },
    thirdName: undefined,
    partyType: "A",
    religionId: 0,
    fourName: undefined,
    industryId: 0,
    occupationId: 0,
    custTitleId: 0,
    custId: 120265000,
    state: "A",
    email: undefined,
    secondName: undefined,
    comments: undefined,
    address: undefined,
    netType: "A",
    certId: 120011000,
    custName: "Development Test",
    spId: undefined,
    custCode: "1120265000",
    parentId: 0,
    zipcode: undefined,
    firstName: undefined,
    areaId: undefined,
    createdDate: "2025/09/26 00:00:00",
    phoneNumber: undefined,
    birthdayDay: undefined,
    partyCode: "1",
    custType: "A",
    custCreditGradeId: 0,
    stateDate: "2025/09/26 00:00:00",
    pwd: "QFfpQMMfO6o=",
    stdAddrId: undefined,
  },
  firstCall: undefined,
  fellowNbrExList: undefined,
  subsRelaExList: undefined,
  oweFee: undefined,
  subsPlanAttrXml:
    '<?xml version="1.0" encoding="UTF-8"?>\r\n<Properties><Property code="TECL_USER_TYPE" comments=undefined defaultValue="0" displayName="User Type" editable="false" id="400001" instantiatable="false" multipleChoice="false" nullable="false" type="ComboBox" visible="true"><Item text="Prepaid" value="0"></Item><Item text="Postpaid" value="1"></Item><Item text="Hybrid" value="2"></Item></Property></Properties>',
  offer: {
    cycleQuantity: undefined,
    saleListPrice: undefined,
    expDate: undefined,
    expTimeUnit: undefined,
    offerType: "2",
    effDate: "2023/07/01 00:00:00",
    effType: undefined,
    agreementEffType: undefined,
    salePriceGstType: undefined,
    state: "A",
    timeUnit: undefined,
    comments: "90D->180D->33D->90D",
    offerName: "Telkomcel Prepaid Channel",
    prodType: undefined,
    spId: 0,
    rentPriceGstType: undefined,
    rentListPrice: undefined,
    createdDate: "2023/07/26 10:42:59",
    offerCode: "MP_1000",
    autoContinueFlag: undefined,
    offerId: 4,
    duplicateFlag: undefined,
    expOff: undefined,
    stateDate: "2023/07/26 10:42:59",
    specTime: undefined,
  },
  subsGoodsInstExList: undefined,
  timer: undefined,
  usedResExList: [
    {
      resNbr: "74747299",
      createdDate: "2025/04/10 17:44:31",
      resTypeName: "NUMBER",
      usedResId: 120305000,
      resType: "A",
      stateDate: "2025/04/10 17:44:31",
      state: "A",
      prodId: 121299005,
      resId: 1020161,
      spId: 0,
    },
    {
      resNbr: "8967011700011056573F",
      createdDate: "2025/04/10 17:44:31",
      resTypeName: "SIM CARD",
      usedResId: 120305001,
      resType: "B",
      stateDate: "2025/04/10 17:44:31",
      state: "A",
      prodId: 121299005,
      resId: 1020161,
      spId: 0,
    },
  ],
  subsPlanOffer: {
    cycleQuantity: undefined,
    saleListPrice: undefined,
    expDate: undefined,
    expTimeUnit: undefined,
    offerType: "7",
    effDate: "2023/07/01 00:00:00",
    effType: undefined,
    agreementEffType: undefined,
    salePriceGstType: undefined,
    state: "A",
    timeUnit: undefined,
    comments: undefined,
    offerName: "SC_1000_Prepaid_Reguler",
    prodType: undefined,
    spId: 0,
    rentPriceGstType: undefined,
    rentListPrice: undefined,
    createdDate: "2023/07/26 15:37:27",
    offerCode: "1000",
    autoContinueFlag: "N",
    offerId: 360,
    duplicateFlag: undefined,
    expOff: undefined,
    stateDate: "2023/07/26 15:37:27",
    specTime: undefined,
  },
  ccSubsExList: undefined,
  postPaidFlag: undefined,
  dependProdExList: [
    {
      agreementExpDate: undefined,
      prodExList: undefined,
      updateDate: "2025/09/26 16:28:29",
      routingId: undefined,
      parentOfferId: undefined,
      needUpload: undefined,
      prodId: 121308009,
      prodState: "A",
      prodAlias: undefined,
      offerType: "3",
      paramStartDate: undefined,
      prodStateDate: "2025/09/26 16:28:29",
      prodExpDate: undefined,
      activeDate: undefined,
      uploadType: undefined,
      indepProdId: undefined,
      paramEndDate: undefined,
      state: "A",
      agreementLimit: undefined,
      blockReason: undefined,
      offerName: "Incoming SMS",
      paramExactDate: undefined,
      spId: undefined,
      completedDate: "2025/09/26 16:28:29",
      subsPlanId: undefined,
      createdDate: "2025/09/26 16:28:29",
      packageFlag: "N",
      agreementEffDate: undefined,
      offerCode: "SMMT",
      agreementTimeUnit: undefined,
      offerId: 74,
      promotionItemId: undefined,
      parentProdId: undefined,
      stateDate: "2025/09/26 16:28:29",
    },
    {
      agreementExpDate: undefined,
      prodExList: undefined,
      updateDate: "2025/09/26 16:28:29",
      routingId: undefined,
      parentOfferId: undefined,
      needUpload: undefined,
      prodId: 121308012,
      prodState: "A",
      prodAlias: undefined,
      offerType: "3",
      paramStartDate: undefined,
      prodStateDate: "2025/09/26 16:28:29",
      prodExpDate: undefined,
      activeDate: undefined,
      uploadType: undefined,
      indepProdId: undefined,
      paramEndDate: undefined,
      state: "A",
      agreementLimit: undefined,
      blockReason: undefined,
      offerName: "Data Service",
      paramExactDate: undefined,
      spId: undefined,
      completedDate: "2025/09/26 16:28:29",
      subsPlanId: undefined,
      createdDate: "2025/09/26 16:28:29",
      packageFlag: "N",
      agreementEffDate: undefined,
      offerCode: "Data Service",
      agreementTimeUnit: undefined,
      offerId: 73,
      promotionItemId: undefined,
      parentProdId: undefined,
      stateDate: "2025/09/26 16:28:29",
    },
    {
      agreementExpDate: undefined,
      prodExList: undefined,
      updateDate: "2025/09/26 16:28:29",
      routingId: undefined,
      parentOfferId: undefined,
      needUpload: undefined,
      prodId: 121308011,
      prodState: "A",
      prodAlias: undefined,
      offerType: "3",
      paramStartDate: undefined,
      prodStateDate: "2025/09/26 16:28:29",
      prodExpDate: undefined,
      activeDate: undefined,
      uploadType: undefined,
      indepProdId: undefined,
      paramEndDate: undefined,
      state: "A",
      agreementLimit: undefined,
      blockReason: undefined,
      offerName: "Voice Service",
      paramExactDate: undefined,
      spId: undefined,
      completedDate: "2025/09/26 16:28:29",
      subsPlanId: undefined,
      createdDate: "2025/09/26 16:28:29",
      packageFlag: "N",
      agreementEffDate: undefined,
      offerCode: "Voice Service",
      agreementTimeUnit: undefined,
      offerId: 72,
      promotionItemId: undefined,
      parentProdId: undefined,
      stateDate: "2025/09/26 16:28:29",
    },
    {
      agreementExpDate: undefined,
      prodExList: undefined,
      updateDate: "2025/09/26 16:28:29",
      routingId: undefined,
      parentOfferId: undefined,
      needUpload: undefined,
      prodId: 121308010,
      prodState: "A",
      prodAlias: undefined,
      offerType: "3",
      paramStartDate: undefined,
      prodStateDate: "2025/09/26 16:28:29",
      prodExpDate: undefined,
      activeDate: undefined,
      uploadType: undefined,
      indepProdId: undefined,
      paramEndDate: undefined,
      state: "A",
      agreementLimit: undefined,
      blockReason: undefined,
      offerName: "Outgoing SMS",
      paramExactDate: undefined,
      spId: undefined,
      completedDate: "2025/09/26 16:28:29",
      subsPlanId: undefined,
      createdDate: "2025/09/26 16:28:29",
      packageFlag: "N",
      agreementEffDate: undefined,
      offerCode: "SMMO",
      agreementTimeUnit: undefined,
      offerId: 75,
      promotionItemId: undefined,
      parentProdId: undefined,
      stateDate: "2025/09/26 16:28:29",
    },
  ],
  depositItemExList: undefined,
  subsHomeZoneExList: undefined,
  subsBaseDetail: {
    agreementExpDate: undefined,
    certTypeName: undefined,
    defLangId: 3,
    prefix: "670",
    certTypeId: undefined,
    prodNextStateDate: "2026/02/02 14:50:24",
    prodState: "A",
    areaName: "Timor-Leste",
    prodStateDate: "2025/09/26 16:28:29",
    prodExpDate: undefined,
    activeDate: undefined,
    indepProdId: 0,
    state: "A",
    blockReason: undefined,
    subsCatgNameList: undefined,
    orgName: "Telkomcel",
    certNbr: undefined,
    acctId: 120255000,
    prodUpdateDate: "2025/09/26 00:00:00",
    prodAttrValueExList: [
      {
        updateDate: undefined,
        routingId: undefined,
        attrCode: "EXP_PHONE_FIRSTCALLTIME",
        needUpload: undefined,
        prodId: 121308008,
        spId: undefined,
        expDate: undefined,
        attrType: "1",
        effDate: "2025/09/26 16:30:17",
        attrId: 260,
        uploadType: undefined,
        inputType: "3",
        value: "2025-09-26 16:30:17",
        attrName: "The Time of First Call",
        key: "2025-09-26 16:30:17",
      },
      {
        updateDate: undefined,
        routingId: undefined,
        attrCode: "EXP_IS_TRUE_CUST_INFO",
        needUpload: undefined,
        prodId: 121308008,
        spId: undefined,
        expDate: undefined,
        attrType: "1",
        effDate: "2025/09/26 16:30:17",
        attrId: 625,
        uploadType: undefined,
        inputType: "1",
        value: "Yes",
        attrName: "True Flag of Cust Info",
        key: "Y",
      },
    ],
    completedDate: "2025/09/26 00:00:00",
    subsPlanId: 360,
    ppsPwd: "PQ77qjgBtaw=",
    offerId: 4,
    parentProdId: 0,
    subsSpecialGroupNameList: undefined,
    subsPlanName: "SC_1000_Prepaid_Reguler",
    agentId: 0,
    updateDate: "2025/09/26 16:28:29",
    routingId: 1,
    prodStateName: "Active",
    prodAttrValueXML:
      '<?xml version="1.0" encoding="UTF-8"?><Properties>  <Property id="121308008" displayName="The Time of First Call" type="TextBox" defaultValue="2025-09-26 16:30:17" nullable="trueundefined editable="false" comments="������������������������������" groupDesc=undefined visible="true" code="EXP_PHONE_FIRSTCALLTIME" instance=undefined> \n  </Property>\n  <Property id="121308008" displayName="True Flag of Cust Info" type="TextBox" defaultValue="Yes" nullable="trueundefined editable="false" comments=undefined groupDesc=undefined visible="false" code="EXP_IS_TRUE_CUST_INFO" instance="Y"> \n  </Property>\n</Properties>',
    imsi: "514010075006594",
    prodId: 121308008,
    orgId: 1,
    blockReasonName: undefined,
    paidFlag: "N",
    custId: 120265000,
    prodNextState: "D",
    accNbr: 73007362,
    servType: "15",
    comments: undefined,
    offerName: undefined,
    custName: undefined,
    userId: 120265000,
    spId: 0,
    subsId: 121308008,
    createdDate: "2025/09/26 00:00:00",
    areaId: 1,
    packageFlag: "N",
    agreementEffDate: "2025/09/26 00:00:00",
    stateDate: "2025/09/26 00:00:00",
    acctNbr: undefined,
  },
};

export const prodStateTrackBeforeMock = [
  {
    rownum: 1,
    subsEventId: 123,
    newProdState: "A",
    updateDate: "2025-04-14 16:50:29",
    oldProdState: "G",
    eventName: "PPS First Dial",
    oldProdStateName: "Inactive",
    newProdStateName: "Active",
  },
  {
    rownum: 2,
    subsEventId: 389,
    newProdState: "D",
    updateDate: "2025-08-31 01:00:08",
    oldProdState: "A",
    eventName: "One-way Block For Balance Expire",
    oldProdStateName: "Active",
    newProdStateName: "Grace",
  },
];

export const prodStateTrackAfterMock = [
  {
    nextStateName: "Grace",
    nextStateDate: "2031/12/31 23:59:59",
    nextState: "D",
    isIndividual: "false",
  },
  {
    nextStateName: "Expiry",
    nextStateDate: "2032/01/30 23:59:59",
    nextState: "E",
    isIndividual: "false",
  },
  {
    nextStateName: "Clearance",
    nextStateDate: "2032/02/29 23:59:59",
    nextState: "C",
    isIndividual: "false",
  },
  {
    nextStateName: "Termination",
    nextStateDate: "2032/03/03 23:59:59",
    nextState: "B",
    isIndividual: "false",
  },
];
