const mockIccidCall = {
  boAccessName: "custOrder",
  commonDataId: "4kt9roobvWTVLyvYEkkCveyvxcatCodh",
  dirtyList: [
    {
      action: "DEFAULT",
      bo: false,
      boAccessName: "orderItem",
      boItemAccessName: "iccid",
      filters: { iccid: {}, orderItem: { orderItemId: 121179281 } },
      flushed: true,
      isRoot: "N",
      location: {
        accessNamePath: "/orderItem/iccid",
        array: false,
        bo: false,
        dataType: "STRING",
        isKeyValue: "N",
        itemAccessName: "iccid",
        itemType: "DI",
        locationItemAccessName: "orderItem",
        parentArray: true,
      },
      orderItemId: 121179281,
      value: "8967011700010295677F", //ini iccid nya
      valueType: "DI",
    },
    {
      action: "DEFAULT",
      bo: false,
      boAccessName: "orderItem",
      boItemAccessName: "simCardId",
      filters: { simCardId: {}, orderItem: { orderItemId: 121179281 } },
      flushed: true,
      isRoot: "N",
      location: {
        accessNamePath: "/orderItem/simCardId",
        array: false,
        bo: false,
        dataType: "INTEGER",
        isKeyValue: "N",
        itemAccessName: "simCardId",
        itemType: "DI",
        locationItemAccessName: "orderItem",
        parentArray: true,
      },
      orderItemId: 121179281,
      value: 1025473,
      valueType: "DI",
    },
  ],
  dsi: {},
  errors: [],
  hints: [],
  rollbackList: [],
};

const mockStartOrderFlowShop = {
  boAccessName: "custOrder",
  commonDataId: "q2fyKCqTvmpZZmwNnBT0an7c1jGBB1O9",
  dirtyList: [
    {
      action: "OVERRIDE",
      bo: false,
      boAccessName: "custOrder",
      filters: {},
      flushed: false,
      isRoot: "Y",
      location: {
        accessNamePath: "/",
        array: false,
        bo: true,
        dataType: "BO",
        includeObjectId: "2f20e016-f047-4677-abe6-7df4b370f121",
        itemAccessName: "custOrder",
        itemType: "VI",
        parentArray: false,
      },
      value: {
        SERV_TYPE: "15",
        CUST_ID: 120265000,
        CREATED_DATE: "2026-01-30 16:32:12",
        SP_ID: 0,
        ACCEPT_DATE: "2026-01-30 16:32:12",
        ACCT: [
          {
            PAYMENT_METHOD_ID: 1,
            CUST_ID: 120265000,
            ROUTING_ID: 1,
            ACCT_ID: 120255000,
            STATE: "A",
            BILLING_CYCLE_TYPE_ID: 1,
            PAYMENT_TYPE: "A",
            DEFAULT_FLAG: "N",
            PARTY_TYPE: "A",
            ACCT_NBR: "930255000",
            POSTPAID: "N",
            PARTY_CODE: "1",
          },
        ],
        CUST_ORDER_ID: 121220530,
        ROUTING_ID: 1,
        OFFER_ID: "4",
        POS_SALE_MODE: 1,
        CONTACT_CHANNEL_ID: 1,
        A_PARTY_CODE: "120265000",
        ORDER_ITEM: [
          {
            SERV_TYPE: 15,
            DP_OFFER_ORDER: [
              {
                SP_ID: 0,
                OFFER_TYPE: "3",
                EFF_TYPE: "B",
                OFFER_GROUP_ID: 1,
                OFFER_NAME: "Incoming SMS",
                OFFER_ID: 74,
                OPERATION_TYPE: "A",
                OFFER_SEQ: "f8734863-3dfb-47ed-bc65-90393b478bf9",
                ORDER_ITEM_ID: 121179283,
              },
              {
                SP_ID: 0,
                OFFER_TYPE: "3",
                EFF_TYPE: "B",
                OFFER_GROUP_ID: 1,
                OFFER_NAME: "Outgoing SMS",
                OFFER_ID: 75,
                OPERATION_TYPE: "A",
                OFFER_SEQ: "6cbd4653-928c-4c8a-bb94-8ea62b46e71f",
                ORDER_ITEM_ID: 121179283,
              },
              {
                SP_ID: 0,
                OFFER_TYPE: "3",
                EFF_TYPE: "B",
                OFFER_GROUP_ID: 1,
                OFFER_NAME: "Voice Service",
                OFFER_ID: 72,
                OPERATION_TYPE: "A",
                OFFER_SEQ: "7e3e0b88-bd39-48cb-a953-0e05ccb352bf",
                ORDER_ITEM_ID: 121179283,
              },
              {
                SP_ID: 0,
                OFFER_TYPE: "3",
                EFF_TYPE: "B",
                OFFER_GROUP_ID: 1,
                OFFER_NAME: "Data Service",
                OFFER_ID: 73,
                OPERATION_TYPE: "A",
                OFFER_SEQ: "8d8f0793-3404-4444-86da-e8e6ef761bc5",
                ORDER_ITEM_ID: 121179283,
              },
              {
                DP_OFFER_ORDER_ATTR: [
                  {
                    ATTR_VALUE: "1",
                    ATTR_NAME: "exp type precision second",
                    ATTR_ID: 624,
                    OPERATION_TYPE: "A",
                    VALUE_MARK: "precision to second",
                  },
                ],
                SP_ID: 0,
                OFFER_TYPE: "4",
                EFF_TYPE: "B",
                OFFER_GROUP_ID: 83,
                OFFER_NAME: "Prepaid_Telkomcel_FURAK_DPP",
                OFFER_ID: 120,
                OPERATION_TYPE: "A",
                OFFER_SEQ: "43d91cf0-1cf9-417a-8330-61fea51dff7f",
                ORDER_ITEM_ID: 121179283,
              },
            ],
            ACCT: {
              PAYMENT_METHOD_ID: 1,
              CUST_ID: 120265000,
              ROUTING_ID: 1,
              ACCT_ID: 120255000,
              STATE: "A",
              BILLING_CYCLE_TYPE_ID: 1,
              PAYMENT_TYPE: "A",
              DEFAULT_FLAG: "N",
              PARTY_TYPE: "A",
              ACCT_NBR: "930255000",
              POSTPAID: "N",
              PARTY_CODE: "1",
            },
            SUBS_PLAN_NAME: "SC_1111_Prepaid_Telkomcel_FURAK",
            CUST_ORDER_ID: 121220530,
            OFFER_ID: 4,
            CONTACT_CHANNEL_ID: 1,
            INDEP_PROD_ORDER_ATTR: [
              {
                ATTR_VALUE: "0",
                SP_ID: 0,
                ATTR_ID: 400001,
                ORDER_ITEM_ID: 121179283,
                OPERATION_TYPE: "A",
              },
            ],
            IS_CHECK_OWE_CHARGE: true,
            SUBS_EVENT_ID: 1,
            ORDER_NBR: "2026013021179283",
            ACCT_ID: 120255000,
            IS_RESERVE: false,
            ORDER_TYPE: "B",
            OPERATION_TYPE: "A",
            SUBS_PLAN_ID: 401,
            CUST_ID: 120265000,
            SP_ID: 0,
            STATE_DATE: "2026-01-30 16:32:12",
            ORDER_STATE: "I",
            POS_SALE_MODE: 1,
            IS_SAVED: true,
            POSTPAID: "N",
            SUBS_BASE_ORDER: {
              SERV_TYPE: 15,
              CUST_ID: 120265000,
              ORG_ID: 1,
              USER_ID: 120265000,
              SUBS_PLAN_NAME: "SC_1111_Prepaid_Telkomcel_FURAK",
              AREA_NAME: "Timor-Leste",
              DEF_LANG_ID: 2,
              POSTPAID: "N",
              AREA_ID: 1,
              DEF_LANG_NAME: "Tetun",
              INDEP_PROD_SPEC_ID: 4,
              ACCT_ID: 120255000,
              USER_NAME: "Development Test",
              OPERATION_TYPE: "A",
              SUBS_PLAN_ID: 401,
              ORDER_ITEM_ID: 121179283,
              ACCT_NBR: "930255000",
              CUST_NAME: "Development Test",
            },
            SUBS_ID: 121312007,
            OFFER_NAME: "Telkomcel Prepaid Channel",
            ORDER_ITEM_ID: 121179283,
            CUST_NAME: "Development Test",
          },
        ],
        CUST: {
          CUST_ID: 120265000,
          ROUTING_ID: 1,
          CUST_TYPE: "A",
          CUST_CODE: "1120265000",
          CERT_ID: 120011000,
          CUST_NAME: "Development Test",
        },
        SUBS_EVENT_ID: "1",
        CUST_CONTACT: {
          CUST_ID: 120265000,
          CREATED_DATE: "2026-01-30 16:32:12",
          SP_ID: 0,
          PARTY_TYPE: "A",
          CUST_CONTACT_ID: 187457330,
          CONTACT_TYPE: "A",
          CONTACT_CHANNEL_ID: 1,
          RELA_ID: 121220530,
          CONTACT_EVENT_ID: "A",
          PARTY_CODE: "1",
        },
        PARTY_TYPE: "A",
        SEND_PROVISIONING_FLAG: "Y",
        CUST_ORDER_NBR: "121220530",
        CREDIT_LIMIT_MODE: "0",
        A_PARTY_TYPE: "D",
        STAFF_INFO: { AREA_ID: 1, ORG_ID: 1, STAFF_ID: 1, STAFF_JOB_ID: 1 },
        PARTY_CODE: "1",
      },
      valueType: "VI",
    },
  ],
  dsi: {},
  errors: [],
  hints: [],
  rollbackList: [],
  wizardPage: {
    accessName:
      "com.ztesoft.zsmart.bss.fiji.cc.orderentry.offer.shoppingcart.subscription.SubscriptionDetail",
    accessPath:
      "fiji/customercare/sharepage/flowpage/orderentry/SubscriptionDetailPage.swf",
    canBackward: false,
    canForward: true,
    code: "SubscriptionDetail",
    id: "SubscriptionDetail",
    properties: {},
  },
};

const mockStartOrderFlowReq = {
  commonDataId: null,
  boId: null,
  sysEvent: null,
  templateId: null,
  dataChangeList: [
    {
      event: null,
      boId: null,
      boInstId: null,
      locationItemId: null,
      boItemId: null,
      boAccessName: "custOrder",
      boItemAccessName: null,
      oldValue: null,
      value: {
        OFFER_ID: "4",
        SUBS_EVENT_ID: "1",
        AREA_ID: "1",
        ORG_ID: 1,
        STAFF_JOB_ID: 1,
        STAFF_ID: 1,
        SUBS_PLAN_ID: "401",
        OFFER_VER_ID: "324",
        SERV_TYPE: "15",
        CUST_ID: "120265000",
        CUST_NAME: "Development Test",
        INDEP_PROD_SPEC_ID: "4",
        CONTACT_CHANNEL_ID: "1",
        CHANNEL_TYPE: "1",
        SP_ID: 0,
      },
      orderItemId: null,
      arrayKeyField: null,
      operationType: "A",
      parentKeyValue: null,
      bo: true,
    },
  ],
  requestDsi: false,
  refreshDirty: true,
  action: "START_ORDER_FLOW",
  bfmKey: "q2fyKCqTvmpZZmwNnBT0an7c1jGBB1O9",
};
