import { AcctResList, BalanceDetail, ValidBallExchangeRule } from "./interfaces";

export const mockAccountBallDetail: BalanceDetail[] = [
  {
    updateDate: "2025/11/04 16:53:34",
    expDate: "2026/02/02 14:50:24",
    effDate: "2025/09/26 00:00:00",
    seconds: "0",
    reserveBal: 0,
    acctRes: {
      adjustType: "7",
      balType: "1",
      maxValue: "100000000000",
      acctResName: "Main balance",
      freeFlag: "N",
      stdCode: "0",
      balCategory: "M",
      acctResId: 1,
      unitTypeId: 4,
      customerFlag: "N",
      unitType: {
        unitTypeId: 4,
        unitCode: "$",
        unitTypeName: "$",
        trafficType: 1,
        stateDate: "2023/07/26 09:50:18",
        state: "A",
      },
      refillable: "Y",
      isCurrency: "Y",
      isFreeUnit: "N",
      clearFlag: "N",
      balanceAggregation: "N",
      spId: "0",
      unlimitedFlag: "N",
      paymentForce: "N",
      rewardFlag: "N",
      extendRule: "000000",
      rolloverFlag: "N",
    },
    isCurrency: "Y",
    balId: 11372039,
    acctResName: "Main balance",
    charge: 0,
    usedBal: 0,
    lastBal: 0,
    consumeBal: 0,
    realBal: -100000,
    balUsed: 0,
    acctId: 120255000,
    billingBal: 0,
    subsId: -1,
    balShareInWorkHourFlag: "Y",
    acctResId: 1,
    ratingBal: 0,
    grossBal: -100000,
    initBal: -100000,
  },
  {
    updateDate: "2025/10/22 11:15:21",
    expDate: "2025/12/31 23:59:59",
    effDate: "2025/10/20 12:17:47",
    seconds: "0",
    reserveBal: 0,
    acctRes: {
      adjustType: "7",
      balType: "4",
      acctResName: "Telkomcel Point",
      freeFlag: "Y",
      stdCode: "4001",
      balCategory: "P",
      acctResId: 21,
      unitTypeId: 5,
      unitType: {
        unitTypeId: 5,
        unitCode: "Point",
        unitTypeName: "Point",
        stateDate: "2023/07/27 10:14:42",
        state: "A",
      },
      refillable: "L",
      isCurrency: "N",
      isFreeUnit: "N",
      clearFlag: "Y",
      balanceAggregation: "N",
      spId: "0",
      unlimitedFlag: "N",
      paymentForce: "N",
      clearDays: "2",
      rewardFlag: "N",
      extendRule: "000000",
      rolloverFlag: "N",
    },
    isCurrency: "N",
    balId: 11372067,
    acctResName: "Telkomcel Point",
    charge: 0,
    usedBal: 0,
    lastBal: 0,
    consumeBal: 0,
    realBal: -7,
    balUsed: 0,
    acctId: 120255000,
    billingBal: 0,
    subsId: -1,
    balShareInWorkHourFlag: "Y",
    acctResId: 21,
    ratingBal: 0,
    grossBal: -7,
    initBal: -7,
  },
];

export const mockBalanceExchangeRule: ValidBallExchangeRule[] = [
  {
    effDate: "2026-02-12 00:00:00",
    balExchangeRuleId: "1",
    srcAcctResId: 1,
    objValue: 50000,
    balExchangeRuleName: "Testing Exchange Rule",
    exchangeType: "P",
    srcValue: 100000,
    objExpOffsetType: "N",
    objAcctResId: "22",
  },
];

export const mockObjAccountType: AcctResList[] = [
  {
    balType: "4",
    refillable: "L",
    acctResName: "Balance Type For Testing",
    acctResId: "1901",
    isCurrency: "N",
  },
  {
    stdCode: "9040",
    balType: "5",
    refillable: "L",
    acctResName: "Bonus  100% Rapido Turbo",
    acctResId: "601",
    isCurrency: "N",
  },
  {
    stdCode: "1015",
    balType: "3",
    refillable: "L",
    acctResName: "Bonus - Etopup Refill",
    acctResId: "64",
    isCurrency: "Y",
  },
  {
    stdCode: "1012",
    balType: "3",
    refillable: "L",
    acctResName: "Bonus - SC Student",
    acctResId: "63",
    isCurrency: "Y",
  },
  {
    stdCode: "7077",
    balType: "5",
    refillable: "L",
    acctResName: "Bonus 99",
    acctResId: "602",
    isCurrency: "N",
  },
  {
    stdCode: "BBT01",
    comments: "test",
    balType: "5",
    refillable: "L",
    acctResName: "Bonus Balance Test",
    acctResId: "2001",
    isCurrency: "N",
    parentAcctResId: "60",
  },
  {
    stdCode: "1010",
    balType: "3",
    refillable: "L",
    acctResName: "Bonus Bundling LowEnd & MidEnd",
    acctResId: "58",
    isCurrency: "Y",
  },
  {
    stdCode: "7001",
    comments: "Internet, all access",
    balType: "5",
    refillable: "L",
    acctResName: "Bonus Data",
    acctResId: "6",
    isCurrency: "N",
  },
  {
    stdCode: "BD01",
    balType: "4",
    refillable: "L",
    acctResName: "Bonus Data 2",
    acctResId: "2201",
    isCurrency: "N",
  },
  {
    stdCode: "7041",
    comments: "Internet, for access Sosmed",
    balType: "5",
    refillable: "L",
    acctResName: "Bonus Double Qouta Sosmed",
    acctResId: "70",
    isCurrency: "N",
  },
  {
    stdCode: "7060",
    comments: "Internet, all access",
    balType: "5",
    refillable: "L",
    acctResName: "Bonus I Love Monday",
    acctResId: "112",
    isCurrency: "N",
  },
  {
    stdCode: "1011",
    balType: "3",
    refillable: "L",
    acctResName: "Bonus Independence day $17",
    acctResId: "119",
    isCurrency: "Y",
  },
  {
    stdCode: "1002",
    balType: "3",
    refillable: "L",
    acctResName: "Bonus Monetary",
    acctResId: "85",
    isCurrency: "Y",
  },
  {
    stdCode: "1003",
    balType: "3",
    refillable: "L",
    acctResName: "Bonus Monetary (Sunday TopUp)",
    acctResId: "7",
    isCurrency: "Y",
  },
  {
    stdCode: "1001",
    balType: "3",
    refillable: "L",
    acctResName: "Bonus Monetary Monthly",
    acctResId: "8",
    isCurrency: "Y",
  },
  {
    stdCode: "7038",
    comments: "Internet, all access",
    balType: "5",
    refillable: "L",
    acctResName: "Bonus MyTimor",
    acctResId: "62",
    isCurrency: "N",
  },
  {
    stdCode: "7022",
    comments: "Voice Off-net",
    balType: "4",
    refillable: "L",
    acctResName: "Bonus Off-net Flash Monthly",
    acctResId: "36",
    isCurrency: "N",
  },
  {
    stdCode: "2008",
    balType: "4",
    refillable: "L",
    acctResName: "Bonus On-net Flash Monthly",
    acctResId: "35",
    isCurrency: "N",
  },
  {
    stdCode: "7059",
    comments: "Internet, all access",
    balType: "5",
    refillable: "L",
    acctResName: "Bonus RaFI 00H-18H",
    acctResId: "111",
    isCurrency: "N",
  },
  {
    stdCode: "1016",
    balType: "2",
    refillable: "L",
    acctResName: "Bonus Recharge",
    acctResId: "65",
    isCurrency: "Y",
  },
  {
    stdCode: "3008",
    balType: "4",
    refillable: "L",
    acctResName: "Bonus SMS",
    acctResId: "5",
    isCurrency: "N",
  },
  {
    stdCode: "7065",
    comments: "Socmed: Facebook, messenger, Instagram, Whatsapp",
    balType: "5",
    refillable: "L",
    acctResName: "Bonus Socmed",
    acctResId: "125",
    isCurrency: "N",
  },
  {
    stdCode: "7025",
    comments: "Access to Vidio.com",
    balType: "5",
    refillable: "L",
    acctResName: "Bonus Vidio.com",
    acctResId: "43",
    isCurrency: "N",
  },
  {
    stdCode: "2012",
    balType: "4",
    refillable: "L",
    acctResName: "Bonus Voice",
    acctResId: "101",
    isCurrency: "N",
  },
  {
    stdCode: "2001",
    balType: "4",
    refillable: "L",
    acctResName: "Bonus Voice FoneHause 3 days",
    acctResId: "47",
    isCurrency: "N",
  },
  {
    stdCode: "1013",
    balType: "3",
    refillable: "L",
    acctResName: "Bonus aktivasi New SIM Card",
    acctResId: "37",
    isCurrency: "Y",
  },
  {
    stdCode: "7012",
    comments: "Internet, all access",
    balType: "5",
    refillable: "L",
    acctResName: "Bonus quota Bundling Furak",
    acctResId: "25",
    isCurrency: "N",
  },
  {
    stdCode: "7020",
    comments: "Internet, all access",
    balType: "5",
    refillable: "L",
    acctResName: "Bonus quota SC Acquisition",
    acctResId: "33",
    isCurrency: "N",
  },
  {
    stdCode: "7034",
    comments: "Internet, all access",
    balType: "5",
    refillable: "L",
    acctResName: "BonusTurbo tinan7",
    acctResId: "56",
    isCurrency: "N",
  },
  {
    stdCode: "7063",
    comments: "Internet, all access",
    balType: "5",
    refillable: "L",
    acctResName: "CPE Bundling MiFi 3G & 4G",
    acctResId: "118",
    isCurrency: "N",
  },
  {
    stdCode: "7037",
    comments: "Internet, all access",
    balType: "5",
    refillable: "L",
    acctResName: "CPE Bundling Router 3G & 4G",
    acctResId: "61",
    isCurrency: "N",
  },
  {
    stdCode: "2011",
    balType: "4",
    refillable: "L",
    acctResName: "Combo Data",
    acctResId: "103",
    isCurrency: "N",
  },
  {
    stdCode: "1007",
    balType: "3",
    refillable: "L",
    acctResName: "Commitment Fee",
    acctResId: "107",
    isCurrency: "Y",
  },
  {
    balType: "7",
    refillable: "L",
    acctResName: "Currency Balance Group",
    acctResId: "201",
    isCurrency: "Y",
  },
  {
    balType: "7",
    refillable: "L",
    acctResName: "Currency Balance Group Internet Access",
    acctResId: "202",
    isCurrency: "Y",
  },
  {
    balType: "7",
    refillable: "L",
    acctResName: "Currency Balance Group Onnet Services",
    acctResId: "203",
    isCurrency: "Y",
  },
  {
    balType: "7",
    acctResName: "Currency Bonus Balance Group",
    acctResId: "1101",
    isCurrency: "Y",
  },
  {
    stdCode: "1005",
    balType: "2",
    refillable: "L",
    acctResName: "DA Enterprise",
    acctResId: "83",
    isCurrency: "Y",
  },
  {
    stdCode: "7010",
    comments: "Internet, all access",
    balType: "5",
    refillable: "L",
    acctResName: "Data Bonus Exchange from Telkomcel Point",
    acctResId: "19",
    isCurrency: "N",
  },
  {
    stdCode: "7043",
    comments: "Internet, all access when in roaming country (when roaming outside TL or Indonesia) - Roaming Dual IMSI",
    balType: "4",
    refillable: "L",
    acctResName: "Data Roaming America Africa 2.45 GB",
    acctResId: "74",
    isCurrency: "N",
  },
  {
    stdCode: "7029",
    comments: "Internet, all access when in roaming country (when roaming outside TL or Indonesia) - Roaming Dual IMSI",
    balType: "4",
    refillable: "L",
    acctResName: "Data Roaming Asia",
    acctResId: "48",
    isCurrency: "N",
  },
  {
    stdCode: "7048",
    comments: "Internet, all access when in roaming country (when roaming outside TL or Indonesia) - Roaming Dual IMSI",
    balType: "4",
    refillable: "L",
    acctResName: "Data Roaming Asia Australia 1 GB",
    acctResId: "88",
    isCurrency: "N",
  },
  {
    stdCode: "7049",
    comments: "Internet, all access when in roaming country (when roaming outside TL or Indonesia) - Roaming Dual IMSI",
    balType: "4",
    refillable: "L",
    acctResName: "Data Roaming Asia Australia 2.5 GB",
    acctResId: "89",
    isCurrency: "N",
  },
  {
    stdCode: "7047",
    comments: "Internet, all access when in roaming country (when roaming outside TL or Indonesia) - Roaming Dual IMSI",
    balType: "4",
    refillable: "L",
    acctResName: "Data Roaming Asia Australia 200MB",
    acctResId: "87",
    isCurrency: "N",
  },
  {
    stdCode: "7050",
    comments: "Internet, all access when in roaming country (when roaming outside TL or Indonesia) - Roaming Dual IMSI",
    balType: "4",
    refillable: "L",
    acctResName: "Data Roaming Asia Australia 5 GB",
    acctResId: "90",
    isCurrency: "N",
  },
  {
    stdCode: "7042",
    comments: "Internet, all access when in roaming country (when roaming outside TL or Indonesia) - Roaming Dual IMSI",
    balType: "4",
    refillable: "L",
    acctResName: "Data Roaming Europe",
    acctResId: "71",
    isCurrency: "N",
  },
  {
    stdCode: "7066",
    comments: "Internet, all access when in roaming country (when roaming outside TL or Indonesia) - Roaming Dual IMSI",
    balType: "4",
    refillable: "L",
    acctResName: "Data Roaming Europe America 5GB",
    acctResId: "126",
    isCurrency: "N",
  },
  {
    stdCode: "7046",
    comments: "Internet, all access when in roaming country (when roaming outside TL or Indonesia) - Roaming Dual IMSI",
    balType: "4",
    refillable: "L",
    acctResName: "Data Roaming Middle East 10GB",
    acctResId: "81",
    isCurrency: "N",
  },
  {
    stdCode: "7045",
    comments: "Internet, all access when in roaming country (when roaming outside TL or Indonesia) - Roaming Dual IMSI",
    balType: "4",
    refillable: "L",
    acctResName: "Data Roaming Middle East 5G",
    acctResId: "80",
    isCurrency: "N",
  },
  {
    stdCode: "7044",
    comments: "Internet, all access when in roaming country (when roaming outside TL or Indonesia) - Roaming Dual IMSI",
    balType: "4",
    refillable: "L",
    acctResName: "Data Roaming Paket Haji",
    acctResId: "77",
    isCurrency: "N",
  },
  {
    balType: "4",
    refillable: "L",
    acctResName: "FUP Balance Test",
    acctResId: "1801",
    isCurrency: "N",
  },
  {
    stdCode: "7061",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Flag Unlimited Flash Monthly",
    acctResId: "113",
    isCurrency: "N",
  },
  {
    stdCode: "7054",
    comments: "Internet, all access",
    balType: "4",
    refillable: "N",
    acctResName: "Flag of Happy Day",
    acctResId: "99",
    isCurrency: "N",
  },
  {
    balType: "7",
    refillable: "N",
    acctResName: "Free Local Bonus Data Balance Group",
    acctResId: "510",
    isCurrency: "N",
  },
  {
    balType: "7",
    refillable: "L",
    acctResName: "Free Local Onnet SMS Group",
    acctResId: "206",
    isCurrency: "N",
  },
  {
    balType: "7",
    refillable: "L",
    acctResName: "Free Local Packages Data Balance Group",
    acctResId: "208",
    isCurrency: "N",
  },
  {
    balType: "7",
    refillable: "L",
    acctResName: "Free Off Net SMS Group",
    acctResId: "207",
    isCurrency: "N",
  },
  {
    balType: "7",
    refillable: "L",
    acctResName: "Free Voice Group for Offnet Call",
    acctResId: "205",
    isCurrency: "N",
  },
  {
    balType: "7",
    refillable: "L",
    acctResName: "Free Voice Group for Onnet Call",
    acctResId: "204",
    isCurrency: "N",
  },
  {
    stdCode: "9029",
    balType: "4",
    refillable: "L",
    acctResName: "HYBRID Unlimited Baratu Monthly",
    acctResId: "522",
    isCurrency: "N",
  },
  {
    stdCode: "9031",
    balType: "4",
    refillable: "L",
    acctResName: "HYBRID Unlimited Baratu Monthly FUP",
    acctResId: "512",
    isCurrency: "N",
  },
  {
    stdCode: "9034",
    balType: "4",
    refillable: "L",
    acctResName: "HYBRID Unlimited Demais Monthly",
    acctResId: "524",
    isCurrency: "N",
  },
  {
    stdCode: "9035",
    balType: "4",
    refillable: "L",
    acctResName: "HYBRID Unlimited Demais Monthly FUP",
    acctResId: "514",
    isCurrency: "N",
  },
  {
    stdCode: "9038",
    balType: "4",
    refillable: "L",
    acctResName: "HYBRID Unlimited Flash Monthly",
    acctResId: "526",
    isCurrency: "N",
  },
  {
    stdCode: "9039",
    balType: "4",
    refillable: "L",
    acctResName: "HYBRID Unlimited Flash Monthly FUP",
    acctResId: "516",
    isCurrency: "N",
  },
  {
    stdCode: "7021",
    comments: "Internet, all access",
    balType: "4",
    refillable: "N",
    acctResName: "Happy Day[00:00-08:59]",
    acctResId: "34",
    isCurrency: "N",
  },
  {
    stdCode: "7021",
    comments: "Internet, all access",
    balType: "4",
    refillable: "N",
    acctResName: "Happy Day[09:00-23:59]",
    acctResId: "98",
    isCurrency: "N",
  },
  {
    stdCode: "7072",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Hybrid Auto Data Package 30GB",
    acctResId: "102",
    isCurrency: "N",
  },
  {
    stdCode: "7073",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Hybrid Auto Data Package 50GB",
    acctResId: "104",
    isCurrency: "N",
  },
  {
    stdCode: "7074",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Hybrid Auto Data Package 90GB",
    acctResId: "106",
    isCurrency: "N",
  },
  {
    stdCode: "7064",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Hybrid Combo Data Package",
    acctResId: "122",
    isCurrency: "N",
  },
  {
    stdCode: "3001",
    balType: "4",
    refillable: "L",
    acctResName: "Hybrid Combo SMS Offnet",
    acctResId: "121",
    isCurrency: "N",
  },
  {
    stdCode: "2005",
    balType: "4",
    refillable: "L",
    acctResName: "Hybrid Combo Voice Offnet",
    acctResId: "120",
    isCurrency: "N",
  },
  {
    stdCode: "7062",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Hybrid Mix&Match Auto Data Package",
    acctResId: "117",
    isCurrency: "N",
  },
  {
    stdCode: "3007",
    balType: "4",
    refillable: "L",
    acctResName: "Hybrid Mix&Match Auto SMS Offnet Package",
    acctResId: "116",
    isCurrency: "N",
  },
  {
    stdCode: "2003",
    balType: "4",
    refillable: "L",
    acctResName: "Hybrid Mix&Match Auto Voice Offnet Package",
    acctResId: "115",
    isCurrency: "N",
  },
  {
    stdCode: "1009",
    balType: "2",
    refillable: "L",
    acctResName: "Hybrid Pulsa",
    acctResId: "40",
    isCurrency: "Y",
  },
  {
    stdCode: "2007",
    balType: "4",
    refillable: "L",
    acctResName: "IDD Voice Package",
    acctResId: "23",
    isCurrency: "N",
  },
  {
    stdCode: "999",
    balType: "2",
    refillable: "N",
    acctResName: "Karteira_Digital",
    acctResId: "999",
    isCurrency: "Y",
  },
  {
    stdCode: "std_cd123",
    balType: "4",
    refillable: "L",
    acctResName: "Local Balance Aimutin",
    acctResId: "1701",
    isCurrency: "N",
  },
  {
    stdCode: "0",
    balType: "1",
    refillable: "Y",
    acctResName: "Main balance",
    acctResId: "1",
    isCurrency: "Y",
  },
  {
    stdCode: "1014",
    balType: "3",
    refillable: "L",
    acctResName: "Monetary Bonus Exchange from Telkomcel Point",
    acctResId: "22",
    isCurrency: "Y",
  },
  {
    stdCode: "7035",
    comments: "Internet, all access",
    balType: "5",
    refillable: "L",
    acctResName: "Monthly bonus quota SC Student",
    acctResId: "57",
    isCurrency: "N",
  },
  {
    stdCode: "2015",
    balType: "4",
    refillable: "L",
    acctResName: "Off-net Voice Package",
    acctResId: "105",
    isCurrency: "N",
  },
  {
    stdCode: "7036",
    comments: "Internet, all access",
    balType: "5",
    refillable: "L",
    acctResName: "Other Bonus",
    acctResId: "60",
    isCurrency: "N",
  },
  {
    stdCode: "9026",
    balType: "4",
    refillable: "L",
    acctResName: "POSTPAID Unlimited Baratu Monthly",
    acctResId: "521",
    isCurrency: "N",
  },
  {
    stdCode: "9027",
    balType: "4",
    refillable: "L",
    acctResName: "POSTPAID Unlimited Baratu Monthly FUP",
    acctResId: "511",
    isCurrency: "N",
  },
  {
    stdCode: "9032",
    balType: "4",
    refillable: "L",
    acctResName: "POSTPAID Unlimited Demais Monthly",
    acctResId: "523",
    isCurrency: "N",
  },
  {
    stdCode: "9033",
    balType: "4",
    refillable: "L",
    acctResName: "POSTPAID Unlimited Demais Monthly FUP",
    acctResId: "513",
    isCurrency: "N",
  },
  {
    stdCode: "9037",
    balType: "4",
    refillable: "L",
    acctResName: "POSTPAID Unlimited Flash Monthly",
    acctResId: "525",
    isCurrency: "N",
  },
  {
    stdCode: "9036",
    balType: "4",
    refillable: "L",
    acctResName: "POSTPAID Unlimited Flash Monthly FUP",
    acctResId: "515",
    isCurrency: "N",
  },
  {
    stdCode: "7054",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Package Reward 1",
    acctResId: "94",
    isCurrency: "N",
  },
  {
    stdCode: "7055",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Package Reward 2",
    acctResId: "95",
    isCurrency: "N",
  },
  {
    stdCode: "7056",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Package Reward Unlimited",
    acctResId: "96",
    isCurrency: "N",
  },
  {
    stdCode: "7039",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Package Winback1 $1.00 - 10GB",
    acctResId: "68",
    isCurrency: "N",
  },
  {
    stdCode: "7040",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Package Winback2 $0.50 - 5GB",
    acctResId: "69",
    isCurrency: "N",
  },
  {
    stdCode: "1006",
    balType: "2",
    refillable: "N",
    acctResName: "Postpaid Account",
    acctResId: "100",
    isCurrency: "Y",
  },
  {
    stdCode: "9998",
    balType: "4",
    refillable: "L",
    acctResName: "Postpaid Combo SMS",
    acctResId: "144",
    isCurrency: "N",
  },
  {
    stdCode: "9999",
    balType: "4",
    refillable: "L",
    acctResName: "Postpaid Combo Voice",
    acctResId: "143",
    isCurrency: "N",
  },
  {
    stdCode: "9998",
    comments: "Internet: T-Track apps",
    balType: "4",
    refillable: "L",
    acctResName: "Postpaid T-Track 12 Months",
    acctResId: "153",
    isCurrency: "N",
  },
  {
    stdCode: "9998",
    comments: "Internet: T-Track apps",
    balType: "4",
    refillable: "L",
    acctResName: "Postpaid T-Track 3 Months",
    acctResId: "156",
    isCurrency: "N",
  },
  {
    stdCode: "9998",
    comments: "Internet: T-Track apps",
    balType: "4",
    refillable: "L",
    acctResName: "Postpaid T-Track 6 Months",
    acctResId: "155",
    isCurrency: "N",
  },
  {
    stdCode: "9998",
    comments: "Internet: T-Track apps",
    balType: "4",
    refillable: "L",
    acctResName: "Postpaid T-Track 9 Months",
    acctResId: "154",
    isCurrency: "N",
  },
  {
    stdCode: "7053",
    comments: "Internet, all access",
    balType: "5",
    refillable: "L",
    acctResName: "Promo - Bonus 100% RAPIDO Package",
    acctResId: "93",
    isCurrency: "N",
  },
  {
    stdCode: "1017",
    balType: "3",
    refillable: "L",
    acctResName: "Promo Bonus Recharge 11x",
    acctResId: "97",
    isCurrency: "Y",
  },
  {
    stdCode: "7011",
    comments: "Internet, all access",
    balType: "5",
    refillable: "L",
    acctResName: "Quota 4G/LTE",
    acctResId: "24",
    isCurrency: "N",
  },
  {
    stdCode: "7000",
    comments: "Internet, all access",
    balType: "5",
    refillable: "L",
    acctResName: "Quota Data F10",
    acctResId: "3",
    isCurrency: "N",
  },
  {
    stdCode: "BL1",
    balType: "4",
    refillable: "L",
    acctResName: "Quota Local 1",
    acctResId: "1601",
    isCurrency: "N",
  },
  {
    stdCode: "QL2",
    balType: "4",
    refillable: "L",
    acctResName: "Quota Local 2",
    acctResId: "1602",
    isCurrency: "N",
  },
  {
    stdCode: "QL3",
    balType: "4",
    refillable: "L",
    acctResName: "Quota Local 3",
    acctResId: "1603",
    isCurrency: "N",
  },
  {
    stdCode: "7033",
    comments: "Internet, all access",
    balType: "5",
    refillable: "L",
    acctResName: "Quota Transfer DA",
    acctResId: "55",
    isCurrency: "N",
  },
  {
    stdCode: "7067",
    balType: "4",
    refillable: "L",
    acctResName: "RAPIDO Socmed 1GB",
    acctResId: "401",
    isCurrency: "N",
  },
  {
    stdCode: "7068",
    balType: "4",
    refillable: "L",
    acctResName: "RAPIDO Socmed 250 MB",
    acctResId: "402",
    isCurrency: "N",
  },
  {
    stdCode: "7069",
    balType: "4",
    refillable: "L",
    acctResName: "RAPIDO Socmed 500MB",
    acctResId: "403",
    isCurrency: "N",
  },
  {
    stdCode: "7075",
    balType: "4",
    refillable: "L",
    acctResName: "RAPIDO Socmed 75MB",
    acctResId: "404",
    isCurrency: "N",
  },
  {
    stdCode: "7013",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "RAPIDO Socmed Package",
    acctResId: "26",
    isCurrency: "N",
  },
  {
    stdCode: "7004",
    comments: "Internet, all access",
    balType: "4",
    refillable: "N",
    acctResName: "RAPIDO Unlimited Baratu Daily",
    acctResId: "31",
    isCurrency: "N",
  },
  {
    stdCode: "9030",
    balType: "4",
    refillable: "L",
    acctResName: "RAPIDO Unlimited Baratu Monthly",
    acctResId: "501",
    isCurrency: "N",
  },
  {
    stdCode: "9013",
    balType: "4",
    refillable: "L",
    acctResName: "RAPIDO Unlimited Baratu Monthly FUP",
    acctResId: "502",
    isCurrency: "N",
  },
  {
    stdCode: "9016",
    balType: "4",
    refillable: "L",
    acctResName: "RAPIDO Unlimited Baratu Weekly",
    acctResId: "500",
    isCurrency: "N",
  },
  {
    stdCode: "9014",
    balType: "4",
    refillable: "L",
    acctResName: "RAPIDO Unlimited Baratu Weekly FUP",
    acctResId: "503",
    isCurrency: "N",
  },
  {
    stdCode: "9015",
    balType: "4",
    refillable: "N",
    acctResName: "RAPIDO Unlimited Demais Daily",
    acctResId: "504",
    isCurrency: "N",
  },
  {
    stdCode: "9018",
    balType: "4",
    refillable: "L",
    acctResName: "RAPIDO Unlimited Demais Monthly",
    acctResId: "517",
    isCurrency: "N",
  },
  {
    stdCode: "9017",
    balType: "4",
    refillable: "L",
    acctResName: "RAPIDO Unlimited Demais Monthly FUP",
    acctResId: "505",
    isCurrency: "N",
  },
  {
    stdCode: "9019",
    balType: "4",
    refillable: "L",
    acctResName: "RAPIDO Unlimited Demais Weekly",
    acctResId: "518",
    isCurrency: "N",
  },
  {
    stdCode: "9020",
    balType: "4",
    refillable: "L",
    acctResName: "RAPIDO Unlimited Demais Weekly FUP",
    acctResId: "506",
    isCurrency: "N",
  },
  {
    balType: "7",
    refillable: "N",
    acctResName: "RAPIDO Unlimited FUP Quota Group",
    acctResId: "902",
    isCurrency: "N",
  },
  {
    stdCode: "9021",
    balType: "4",
    refillable: "N",
    acctResName: "RAPIDO Unlimited Flash Daily",
    acctResId: "507",
    isCurrency: "N",
  },
  {
    stdCode: "9023",
    balType: "4",
    refillable: "L",
    acctResName: "RAPIDO Unlimited Flash Monthly",
    acctResId: "519",
    isCurrency: "N",
  },
  {
    stdCode: "9022",
    balType: "4",
    refillable: "L",
    acctResName: "RAPIDO Unlimited Flash Monthly FUP",
    acctResId: "508",
    isCurrency: "N",
  },
  {
    stdCode: "9024",
    balType: "4",
    refillable: "L",
    acctResName: "RAPIDO Unlimited Flash Weekly",
    acctResId: "520",
    isCurrency: "N",
  },
  {
    stdCode: "9025",
    balType: "4",
    refillable: "L",
    acctResName: "RAPIDO Unlimited Flash Weekly FUP",
    acctResId: "509",
    isCurrency: "N",
  },
  {
    stdCode: "9010",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "RAPIDO Unlimited Weekly for Driver MyTimor",
    acctResId: "527",
    isCurrency: "N",
  },
  {
    stdCode: "9006",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "RAPIDO Unlimited Weekly for Driver MyTimor FUP",
    acctResId: "141",
    isCurrency: "N",
  },
  {
    stdCode: "7003",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Rapido ($0.25 - 300MB - Daily)",
    acctResId: "12",
    isCurrency: "N",
  },
  {
    stdCode: "7058",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Rapido ($0.25-80MB - Weekly)",
    acctResId: "109",
    isCurrency: "N",
  },
  {
    stdCode: "7005",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Rapido ($0.75 - 1024MB - Daily)",
    acctResId: "14",
    isCurrency: "N",
  },
  {
    stdCode: "7014",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Rapido ($1.00 - 400MB - Weekly)",
    acctResId: "27",
    isCurrency: "N",
  },
  {
    stdCode: "7017",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Rapido ($10.00 - 5.2GB - Turbo)",
    acctResId: "30",
    isCurrency: "N",
  },
  {
    stdCode: "7008",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Rapido ($100.00 - 65GB - Monthy)",
    acctResId: "17",
    isCurrency: "N",
  },
  {
    stdCode: "7019",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Rapido ($15.00 - 8GB - Monthly)",
    acctResId: "32",
    isCurrency: "N",
  },
  {
    stdCode: "7009",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Rapido ($150.00 - 100GB - Monthly)",
    acctResId: "18",
    isCurrency: "N",
  },
  {
    stdCode: "7015",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Rapido ($2.00 - 900MB - Weekly)",
    acctResId: "28",
    isCurrency: "N",
  },
  {
    stdCode: "7030",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Rapido ($200.00 - 120 GB - Monthly)",
    acctResId: "51",
    isCurrency: "N",
  },
  {
    stdCode: "7006",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Rapido ($25.00 - 14GB - Monthly)",
    acctResId: "15",
    isCurrency: "N",
  },
  {
    stdCode: "7031",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Rapido ($250.00 - 150 GB - Monthly)",
    acctResId: "52",
    isCurrency: "N",
  },
  {
    stdCode: "7032",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Rapido ($300.00 - 180 GB - Monthly)",
    acctResId: "53",
    isCurrency: "N",
  },
  {
    stdCode: "7023",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Rapido ($40 - 24GB - Monthly)",
    acctResId: "41",
    isCurrency: "N",
  },
  {
    stdCode: "7016",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Rapido ($5.00 - 2.5GB - Turbo)",
    acctResId: "29",
    isCurrency: "N",
  },
  {
    stdCode: "7007",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Rapido ($50.00 - 30GB - Monthly)",
    acctResId: "16",
    isCurrency: "N",
  },
  {
    stdCode: "7024",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Rapido ($75 - 48GB - Monthly)",
    acctResId: "42",
    isCurrency: "N",
  },
  {
    stdCode: "7026",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Rapido (Jumbo - Monthly)",
    acctResId: "44",
    isCurrency: "N",
  },
  {
    stdCode: "7051",
    comments: "Internet, all access",
    balType: "4",
    refillable: "L",
    acctResName: "Rapido Daily SC Student ($1 - 3GB )",
    acctResId: "91",
    isCurrency: "N",
  },
  {
    stdCode: "1004",
    balType: "2",
    refillable: "L",
    acctResName: "Rapido Haksolok AHI ($1 - Weekly $50)",
    acctResId: "86",
    isCurrency: "Y",
  },
  {
    stdCode: "10000",
    balType: "4",
    refillable: "N",
    acctResName: "Rapido Monthly 5GB",
    acctResId: "1301",
    isCurrency: "N",
  },
  {
    stdCode: "9007",
    balType: "4",
    refillable: "N",
    acctResName: "Rapido UL Data All In One",
    acctResId: "802",
    isCurrency: "N",
  },
  {
    stdCode: "10003",
    balType: "4",
    refillable: "N",
    acctResName: "Rapido Unlimited Daily",
    acctResId: "1303",
    isCurrency: "N",
  },
  {
    stdCode: "10001",
    balType: "4",
    refillable: "N",
    acctResName: "Rapido Unlimited Daily 300MB",
    acctResId: "1302",
    isCurrency: "N",
  },
  {
    stdCode: "3010",
    balType: "4",
    refillable: "L",
    acctResName: "Roaming Indonesia Call & SMS SMS",
    acctResId: "133",
    isCurrency: "N",
  },
  {
    stdCode: "2010",
    balType: "4",
    refillable: "L",
    acctResName: "Roaming Indonesia Call & SMS Voice",
    acctResId: "132",
    isCurrency: "N",
  },
  {
    balType: "7",
    refillable: "L",
    acctResName: "Roaming outside TL or Indonesia Data Group",
    acctResId: "301",
    isCurrency: "N",
  },
  {
    stdCode: "3005",
    balType: "4",
    refillable: "L",
    acctResName: "SMS Bonus Redemption Telkomcel Point",
    acctResId: "67",
    isCurrency: "N",
  },
  {
    stdCode: "3011",
    comments: "SMS Offnet and IDD",
    balType: "4",
    refillable: "L",
    acctResName: "SMS Combo",
    acctResId: "9",
    isCurrency: "N",
  },
  {
    stdCode: "3012",
    balType: "4",
    refillable: "L",
    acctResName: "SMS On-net quota (F10)",
    acctResId: "2",
    isCurrency: "N",
  },
  {
    stdCode: "3003",
    balType: "4",
    refillable: "L",
    acctResName: "SMS Packet Umroh",
    acctResId: "82",
    isCurrency: "N",
  },
  {
    stdCode: "3004",
    balType: "4",
    refillable: "L",
    acctResName: "SMS Roaming America Africa",
    acctResId: "76",
    isCurrency: "N",
  },
  {
    stdCode: "3013",
    balType: "4",
    refillable: "L",
    acctResName: "SMS Roaming Asia",
    acctResId: "50",
    isCurrency: "N",
  },
  {
    stdCode: "3006",
    balType: "4",
    refillable: "L",
    acctResName: "SMS Roaming Europe",
    acctResId: "73",
    isCurrency: "N",
  },
  {
    stdCode: "3009",
    balType: "4",
    refillable: "L",
    acctResName: "SMS Roaming Package",
    acctResId: "39",
    isCurrency: "N",
  },
  {
    stdCode: "3002",
    balType: "4",
    refillable: "L",
    acctResName: "SMS Roaming Paket Haji",
    acctResId: "79",
    isCurrency: "N",
  },
  {
    stdCode: "10005",
    balType: "4",
    refillable: "L",
    acctResName: "SMS barato",
    acctResId: "1503",
    isCurrency: "N",
  },
  {
    stdCode: "7027",
    comments: "Internet, all access, time of access ...",
    balType: "4",
    refillable: "L",
    acctResName: "SP Bundling Off-Peak Quota",
    acctResId: "45",
    isCurrency: "N",
  },
  {
    stdCode: "7028",
    comments: "Internet, all access, time of access ...",
    balType: "4",
    refillable: "L",
    acctResName: "SP Bundling On-Peak Quota",
    acctResId: "46",
    isCurrency: "N",
  },
  {
    balType: "7",
    refillable: "N",
    acctResName: "Socmed Package Group",
    acctResId: "701",
    isCurrency: "N",
  },
  {
    stdCode: "9998",
    comments: "Internet: T-Track apps",
    balType: "4",
    refillable: "L",
    acctResName: "T-Motion 12 Months",
    acctResId: "145",
    isCurrency: "N",
  },
  {
    stdCode: "9998",
    comments: "Internet: T-Track apps",
    balType: "4",
    refillable: "L",
    acctResName: "T-Motion 3 Months",
    acctResId: "148",
    isCurrency: "N",
  },
  {
    stdCode: "9998",
    comments: "Internet: T-Track apps",
    balType: "4",
    refillable: "L",
    acctResName: "T-Motion 6 Months",
    acctResId: "147",
    isCurrency: "N",
  },
  {
    stdCode: "9998",
    comments: "Internet: T-Track apps",
    balType: "4",
    refillable: "L",
    acctResName: "T-Motion 9 Months",
    acctResId: "146",
    isCurrency: "N",
  },
  {
    balType: "7",
    acctResName: "T-Motion&Track Unimited Data Group",
    acctResId: "1201",
    isCurrency: "N",
  },
  {
    stdCode: "9998",
    comments: "Internet: T-Track apps",
    balType: "4",
    refillable: "L",
    acctResName: "T-Track 12 Months",
    acctResId: "149",
    isCurrency: "N",
  },
  {
    stdCode: "9998",
    comments: "Internet: T-Track apps",
    balType: "4",
    refillable: "L",
    acctResName: "T-Track 3 Months",
    acctResId: "152",
    isCurrency: "N",
  },
  {
    stdCode: "9998",
    comments: "Internet: T-Track apps",
    balType: "4",
    refillable: "L",
    acctResName: "T-Track 6 Months",
    acctResId: "151",
    isCurrency: "N",
  },
  {
    stdCode: "9998",
    comments: "Internet: T-Track apps",
    balType: "4",
    refillable: "L",
    acctResName: "T-Track 9 Months",
    acctResId: "150",
    isCurrency: "N",
  },
  {
    stdCode: "4001",
    balType: "4",
    refillable: "L",
    acctResName: "Telkomcel Point",
    acctResId: "21",
    isCurrency: "N",
  },
  {
    balType: "7",
    acctResName: "Test Group Sergio",
    acctResId: "1506",
    isCurrency: "Y",
  },
  {
    stdCode: "10004",
    balType: "4",
    refillable: "N",
    acctResName: "Test SMS",
    acctResId: "1501",
    isCurrency: "N",
  },
  {
    stdCode: "100015",
    balType: "4",
    refillable: "N",
    acctResName: "Test SMS Sergio",
    acctResId: "1502",
    isCurrency: "N",
  },
  {
    stdCode: "10009",
    balType: "4",
    refillable: "N",
    acctResName: "Test SMS_EGGY",
    acctResId: "1504",
    isCurrency: "N",
  },
  {
    balType: "7",
    acctResName: "Test group 1205",
    acctResId: "1505",
    isCurrency: "Y",
  },
  {
    stdCode: "1008",
    balType: "3",
    refillable: "L",
    acctResName: "UDAN BONUS",
    acctResId: "59",
    isCurrency: "Y",
  },
  {
    stdCode: "9011",
    balType: "4",
    refillable: "N",
    acctResName: "UL IDD Indonesia Voice",
    acctResId: "134",
    isCurrency: "N",
  },
  {
    stdCode: "9005",
    comments: "Internet, all access",
    balType: "4",
    refillable: "N",
    acctResName: "UL Rapido ($0.50 - 500MB - Daily Niki)",
    acctResId: "13",
    isCurrency: "N",
  },
  {
    stdCode: "9008",
    comments: "Internet, all access",
    balType: "4",
    refillable: "N",
    acctResName: "UL Rapido Haksolok (1Hours)",
    acctResId: "20",
    isCurrency: "N",
  },
  {
    stdCode: "9004",
    comments: "Internet, all access",
    balType: "4",
    refillable: "N",
    acctResName: "UL Rapido Haksolok (6Hours)",
    acctResId: "92",
    isCurrency: "N",
  },
  {
    stdCode: "9009",
    comments: "Internet, all access when roaming in Telkomsel Indonesia network",
    balType: "4",
    refillable: "N",
    acctResName: "UL Roaming Indonesia Data",
    acctResId: "129",
    isCurrency: "N",
  },
  {
    balType: "7",
    acctResName: "UL Roaming Indonesia Data Group",
    acctResId: "1002",
    isCurrency: "N",
  },
  {
    stdCode: "9000",
    balType: "4",
    refillable: "N",
    acctResName: "UL Roaming Indonesia Data-Combo",
    acctResId: "704",
    isCurrency: "N",
  },
  {
    stdCode: "9042",
    balType: "4",
    refillable: "N",
    acctResName: "UL Roaming Indonesia SMS",
    acctResId: "131",
    isCurrency: "N",
  },
  {
    balType: "7",
    acctResName: "UL Roaming Indonesia SMS Group",
    acctResId: "1003",
    isCurrency: "N",
  },
  {
    stdCode: "9001",
    balType: "4",
    refillable: "N",
    acctResName: "UL Roaming Indonesia SMS-Combo",
    acctResId: "702",
    isCurrency: "N",
  },
  {
    stdCode: "9012",
    balType: "4",
    refillable: "N",
    acctResName: "UL Roaming Indonesia Voice",
    acctResId: "130",
    isCurrency: "N",
  },
  {
    balType: "7",
    acctResName: "UL Roaming Indonesia Voice Group",
    acctResId: "1004",
    isCurrency: "N",
  },
  {
    stdCode: "9002",
    balType: "4",
    refillable: "N",
    acctResName: "UL Roaming Indonesia Voice-Combo",
    acctResId: "703",
    isCurrency: "N",
  },
  {
    stdCode: "9003",
    comments: "Internet: T-Track apps",
    balType: "4",
    refillable: "N",
    acctResName: "UL T-Motion&Track Data",
    acctResId: "142",
    isCurrency: "N",
  },
  {
    stdCode: "9041",
    comments: "Unlimited Free SMS on-net",
    balType: "4",
    refillable: "N",
    acctResName: "Unlimited Free SMS on-net",
    acctResId: "110",
    isCurrency: "N",
  },
  {
    stdCode: "9028",
    balType: "4",
    refillable: "N",
    acctResName: "Unlimited IDD Telkom Group",
    acctResId: "54",
    isCurrency: "N",
  },
  {
    stdCode: "2013",
    comments: "Offnet call",
    balType: "4",
    refillable: "L",
    acctResName: "Voice Combo",
    acctResId: "10",
    isCurrency: "N",
  },
  {
    stdCode: "2004",
    balType: "4",
    refillable: "L",
    acctResName: "Voice Roaming America Africa",
    acctResId: "75",
    isCurrency: "N",
  },
  {
    stdCode: "2014",
    balType: "4",
    refillable: "L",
    acctResName: "Voice Roaming Asia",
    acctResId: "49",
    isCurrency: "N",
  },
  {
    stdCode: "2002",
    balType: "4",
    refillable: "L",
    acctResName: "Voice Roaming Europe",
    acctResId: "72",
    isCurrency: "N",
  },
  {
    stdCode: "2006",
    balType: "4",
    refillable: "L",
    acctResName: "Voice Roaming Package",
    acctResId: "38",
    isCurrency: "N",
  },
  {
    stdCode: "2009",
    balType: "4",
    refillable: "L",
    acctResName: "Voice Roaming Packet Haji",
    acctResId: "78",
    isCurrency: "N",
  },
  {
    stdCode: "2016",
    balType: "4",
    refillable: "L",
    acctResName: "Voice on-net quota (F10)",
    acctResId: "4",
    isCurrency: "N",
  },
  {
    stdCode: "7002",
    comments: "Internet, all access",
    balType: "5",
    refillable: "L",
    acctResName: "Volume Quota for AD/Reseller",
    acctResId: "11",
    isCurrency: "N",
  },
  {
    stdCode: "7057",
    comments: "Internet: T-Track apps",
    balType: "4",
    refillable: "L",
    acctResName: "t-track",
    acctResId: "108",
    isCurrency: "N",
  },
];
