import { OfferApply } from "../../interface";

export const mock: OfferApply[] = [
  {
    offerTypeName: "Independent Product",
    offerType: "2",
    offerName: "NATAL2024",
    offerId: "2208",
  },
  {
    offerTypeName: "Independent Product",
    offerType: "2",
    offerName: "Test Main Product 1206",
    offerId: "2289",
  },
  {
    offerTypeName: "Independent Product",
    offerType: "2",
    offerName: "Paket Training",
    offerId: "2290",
  },
  {
    offerTypeName: "Independent Product",
    offerType: "2",
    offerName: "RapidoJoel",
    offerId: "2291",
  },
  {
    offerTypeName: "Independent Product",
    offerType: "2",
    offerName: "PIPTEST",
    offerId: "2325",
  },
  {
    offerTypeName: "Independent Product",
    offerType: "2",
    offerName: "Main Product B",
    offerId: "4103",
  },
  {
    offerTypeName: "Independent Product",
    offerType: "2",
    offerName: "Beduku Main Product",
    offerId: "4301",
  },
  {
    offerTypeName: "Independent Product",
    offerType: "2",
    offerName: "Only one Rock",
    offerId: "2292",
  },
  {
    offerTypeName: "Independent Product",
    offerType: "2",
    offerName: "Athy",
    offerId: "2301",
  },
  {
    offerTypeName: "Independent Product",
    offerType: "2",
    offerName: "Student_4_year",
    offerId: "1401",
  },
  {
    offerTypeName: "Independent Product",
    offerType: "2",
    offerName: "New Happy 2",
    offerId: "2232",
  },
  {
    offerTypeName: "Independent Product",
    offerType: "2",
    offerName: "YONA VALENTE",
    offerId: "2233",
  },
  {
    offerTypeName: "Independent Product",
    offerType: "2",
    offerName: "Main Product Offer Regular (no lifecycle)",
    offerId: "3801",
  },
  {
    offerTypeName: "Independent Product",
    offerType: "2",
    offerName: "Main Product Offer T-Track (no lifecycle)",
    offerId: "3802",
  },
  {
    offerTypeName: "Independent Product",
    offerType: "2",
    offerName: "MarioTest",
    offerId: "2269",
  },
  {
    offerTypeName: "Independent Product",
    offerType: "2",
    offerName: "RApido mm",
    offerId: "2287",
  },
  {
    offerTypeName: "Independent Product",
    offerType: "2",
    offerName: "Main Product A",
    offerId: "4102",
  },
  {
    offerTypeName: "Independent Product",
    offerType: "2",
    offerName: "SIM Student 4 Year Validty",
    offerId: "2101",
  },
];

export const mockOwned: OfferApply[] = [
  {
    offerTypeName: "Independent Product",
    offerType: "2",
    offerName: "Test Main Product 1206",
    lifecycleType: "21",
    offerId: "2289",
  },
  {
    offerTypeName: "Independent Product",
    offerType: "2",
    offerName: "New Happy 2",
    lifecycleType: "21",
    offerId: "2232",
  },
];

[
  {
    tableName: "TMP_TAB_37066",
    wholesale: {
      subsEventId: 1,
      orgId: "1",
      reqDate: "2026-04-03 14:55:41",
      offerId: "43",
      partyType: "A",
      partyCode: 1,
      subsPlanId: "399",
      startNbr: "77770042",
      endNbr: "77770042",
      prefix: "670",
      state: "A",
      priority: "200",
      custId: "",
      extAttr: {
        areaId: "1",
        isFile: "N",
        defLangId: "1",
        custId: "",
        dpOfferList: [
          {
            offerSeq: "74-552",
            offerPkgSeq: null,
            offerId: "74",
            servType: "386",
            offerName: "Incoming SMS",
            offerType: "3",
            offerPkgId: "",
            relExpUnit: "",
            relExpOffset: "",
            operationType: "A",
            effType: "B",
            relAgmUnit: "",
            relAgmOffset: "",
            offerGroupId: "1",
            expOffName: "Forever",
            isDuplicateOrder: null,
            offerInstId: "",
            oldOfferPkgId: "",
            absEffDate: "",
            absExpDate: "",
            relEffOffset: "",
            relEffUnit: "",
            agmExpDate: "",
            oldAgmExpDate: "",
            oldEffDate: "",
            oldExpDate: "",
            prodAlias: "",
            className: "",
          },
          {
            offerSeq: "75-553",
            offerPkgSeq: null,
            offerId: "75",
            servType: "385",
            offerName: "Outgoing SMS",
            offerType: "3",
            offerPkgId: "",
            relExpUnit: "",
            relExpOffset: "",
            operationType: "A",
            effType: "B",
            relAgmUnit: "",
            relAgmOffset: "",
            offerGroupId: "1",
            expOffName: "Forever",
            isDuplicateOrder: null,
            offerInstId: "",
            oldOfferPkgId: "",
            absEffDate: "",
            absExpDate: "",
            relEffOffset: "",
            relEffUnit: "",
            agmExpDate: "",
            oldAgmExpDate: "",
            oldEffDate: "",
            oldExpDate: "",
            prodAlias: "",
            className: "",
          },
          {
            offerSeq: "72-554",
            offerPkgSeq: null,
            offerId: "72",
            servType: "138",
            offerName: "Voice Service",
            offerType: "3",
            offerPkgId: "",
            relExpUnit: "",
            relExpOffset: "",
            operationType: "A",
            effType: "B",
            relAgmUnit: "",
            relAgmOffset: "",
            offerGroupId: "1",
            expOffName: "Forever",
            isDuplicateOrder: null,
            offerInstId: "",
            oldOfferPkgId: "",
            absEffDate: "",
            absExpDate: "",
            relEffOffset: "",
            relEffUnit: "",
            agmExpDate: "",
            oldAgmExpDate: "",
            oldEffDate: "",
            oldExpDate: "",
            prodAlias: "",
            className: "",
          },
          {
            offerSeq: "73-556",
            offerPkgSeq: null,
            offerId: "73",
            servType: "139",
            offerName: "Data Service",
            offerType: "3",
            offerPkgId: "",
            relExpUnit: "",
            relExpOffset: "",
            operationType: "A",
            effType: "B",
            relAgmUnit: "",
            relAgmOffset: "",
            offerGroupId: "1",
            expOffName: "Forever",
            isDuplicateOrder: null,
            offerInstId: "",
            oldOfferPkgId: "",
            absEffDate: "",
            absExpDate: "",
            relEffOffset: "",
            relEffUnit: "",
            agmExpDate: "",
            oldAgmExpDate: "",
            oldEffDate: "",
            oldExpDate: "",
            prodAlias: "",
            className: "",
          },
          {
            offerSeq: "218-280",
            offerPkgSeq: null,
            offerId: "218",
            servType: "",
            offerName: "Extend me 1 Month",
            offerType: "4",
            offerPkgId: "",
            relExpUnit: "H",
            relExpOffset: "0",
            operationType: "A",
            effType: "B",
            relAgmUnit: "",
            relAgmOffset: "",
            offerGroupId: "25",
            expOffName: "0 Hour(s)",
            isDuplicateOrder: null,
            offerInstId: "",
            oldOfferPkgId: "",
            absEffDate: "",
            absExpDate: "",
            relEffOffset: "",
            relEffUnit: "",
            agmExpDate: "",
            oldAgmExpDate: "",
            oldEffDate: "",
            oldExpDate: "",
            prodAlias: "",
            className: "",
          },
          {
            isDuplicateOrder: "Y",
            oriOfferSeq: "218-280",
            operationType: "A",
            offerSeq: "218-280-DUPL-1",
            offerId: "218",
            servType: "",
            offerName: "Extend me 1 Month",
            offerType: "4",
            offerPkgId: "",
            effType: "B",
            offerInstId: null,
            parentInstId: null,
            absEffDate: "",
            relExpUnit: "H",
            relExpOffset: "0",
            expOffName: "0 Hour(s)",
            relAgmUnit: "",
            relAgmOffset: "",
            offerGroupId: "25",
            oldOfferPkgId: "",
            absExpDate: "",
            relEffOffset: "",
            relEffUnit: "",
            agmExpDate: "",
            oldAgmExpDate: "",
            oldEffDate: "",
            oldExpDate: "",
            prodAlias: "",
            className: "",
          },
          {
            offerSeq: "2001-281",
            offerPkgSeq: null,
            offerId: "2001",
            servType: "",
            offerName: "Extend Me 15 Days",
            offerType: "4",
            offerPkgId: "",
            relExpUnit: "H",
            relExpOffset: "0",
            operationType: "A",
            effType: "B",
            relAgmUnit: "",
            relAgmOffset: "",
            offerGroupId: "25",
            expOffName: "0 Hour(s)",
            isDuplicateOrder: null,
            offerInstId: "",
            oldOfferPkgId: "",
            absEffDate: "",
            absExpDate: "",
            relEffOffset: "",
            relEffUnit: "",
            agmExpDate: "",
            oldAgmExpDate: "",
            oldEffDate: "",
            oldExpDate: "",
            prodAlias: "",
            className: "",
          },
        ],
        pricePlanId: ["218", "218", "2001"],
        dependProdSpecId: ["74", "75", "72", "73"],
        indepProdAttrList: [
          {
            attrId: 400001,
            value: "0",
            oldValue: null,
            operationType: "A",
            attrValue: "0",
          },
        ],
        dpOfferAttrList: [
          {
            dpOfferOrderAttr: [
              {
                attrId: 624,
                value: "1",
                oldValue: null,
                operationType: "A",
                valueMark: "precision to second",
                oldValueMark: "",
                attrName: "exp type precision second",
                attrValue: "1",
              },
              {
                attrId: 400005,
                value: "feature real 1",
                oldValue: null,
                operationType: "A",
                valueMark: "feature real 1",
                oldValueMark: "",
                attrName: "Location",
                attrValue: "feature real 1",
              },
            ],
            offerId: "218",
          },
          {
            dpOfferOrderAttr: [ 
              {
                attrId: 624,
                value: "1",
                oldValue: null,
                operationType: "A",
                valueMark: "precision to second",
                oldValueMark: "",
                attrName: "exp type precision second",
                attrValue: "1",
              },
              {
                attrId: 400005,
                value: "feature duplicated 1",
                oldValue: null,
                operationType: "A",
                valueMark: "feature duplicated 1",
                oldValueMark: "",
                attrName: "Location",
                attrValue: "feature duplicated 1",
              },
            ],
            offerId: "218",
          },
          {
            dpOfferOrderAttr: [
              {
                attrId: 400005,
                value: "feature real 2",
                oldValue: null,
                operationType: "A",
                valueMark: "feature real 2",
                oldValueMark: "",
                attrName: "Location",
                attrValue: "feature real 2",
              },
              {
                attrId: 617,
                value: "N",
                oldValue: null,
                operationType: "A",
                valueMark: "N",
                oldValueMark: "",
                attrName: "Need Upload to QMDB",
                attrValue: "N",
              },
            ],
            offerId: "2001",
          },
        ],
      },
    },
    zsmart_dubbo_service_name: "BatchPreNewConnection{PN}Fiji",
    zsmart_fish_flag: true,
    zsmart_referer_url: "http://10.210.242.31:8181/portal/",
  },
];
