import { orderInfo, orderState, orderSubsEvent } from "./interface";

export const mock: orderInfo[] = [
  {
    orderType: "B",
    subsPlanName: "SC_1000_Prepaid_Reguler",
    orderNbr: "2025112821178093",
    offerName: "Telkomcel Prepaid Channel",
    // routingId: "",
    orderItemId: 121178093,
    completedDate: "2025-11-28 22:58:53",
    orderState: "C",
    contactChannelId: 1,
    offerType: "2",
    subsEventId: 69,
    createdMan: "IT Center Administrator - admin",
    contactChannelName: "Point of Sale",
    createdDate: "2025-11-28 22:58:22",
    children: "",
    acceptChannelName: "",
    eventName: "SIM Card Restore",
    offerId: 4,
    accNbr: "73007362",
    bundleMemAlias: "",
    custOrderId: 121219828,
    orderStateName: "Completion",
  },
  {
    orderType: "B",
    subsPlanName: "SC_1000_Prepaid_Reguler",
    orderNbr: "2025112821178092",
    offerName: "Telkomcel Prepaid Channel",
    // routingId: "",
    orderItemId: 121178092,
    completedDate: "2025-11-28 22:57:13",
    orderState: "C",
    contactChannelId: 1,
    offerType: "2",
    subsEventId: 68,
    createdMan: "IT Center Administrator - admin",
    contactChannelName: "Point of Sale",
    createdDate: "2025-11-28 22:56:27",
    children: "",
    acceptChannelName: "",
    eventName: "SIM Card Lost",
    offerId: 4,
    accNbr: "73007362",
    bundleMemAlias: "",
    custOrderId: 121219827,
    orderStateName: "Completion",
  },
  {
    orderType: "B",
    subsPlanName: "SC_1000_Prepaid_Reguler",
    orderNbr: "2025112521178073",
    offerName: "Telkomcel Prepaid Channel",
    // routingId: "",
    orderItemId: 121178073,
    completedDate: "2025-11-25 19:04:42",
    orderState: "C",
    contactChannelId: 1,
    offerType: "2",
    subsEventId: 189,
    createdMan: "IT Center Administrator - admin",
    contactChannelName: "Point of Sale",
    createdDate: "2025-11-25 19:03:06",
    children: "",
    acceptChannelName: "",
    eventName: "Modify Subscriber",
    offerId: 4,
    accNbr: "73007362",
    bundleMemAlias: "",
    custOrderId: 121219808,
    orderStateName: "Completion",
  },
  {
    orderType: "B",
    subsPlanName: "SC_1000_Prepaid_Reguler",
    orderNbr: "2025110421177665",
    offerName: "Telkomcel Prepaid Channel",
    // routingId: "",
    orderItemId: 121177665,
    completedDate: "2025-11-04 16:56:24",
    orderState: "C",
    contactChannelId: 1,
    offerType: "2",
    subsEventId: 189,
    createdMan: "IT Center Administrator - admin",
    contactChannelName: "Point of Sale",
    createdDate: "2025-11-04 16:55:41",
    children: "",
    acceptChannelName: "",
    eventName: "Modify Subscriber",
    offerId: 4,
    accNbr: "73007362",
    bundleMemAlias: "",
    custOrderId: 121219641,
    orderStateName: "Completion",
  },
  {
    orderType: "B",
    subsPlanName: "SC_1000_Prepaid_Reguler",
    orderNbr: "2025110421177664",
    offerName: "Telkomcel Prepaid Channel",
    // routingId: "",
    orderItemId: 121177664,
    completedDate: "2025-11-04 16:53:44",
    orderState: "C",
    contactChannelId: 1,
    offerType: "2",
    subsEventId: 189,
    createdMan: "IT Center Administrator - admin",
    contactChannelName: "Point of Sale",
    createdDate: "2025-11-04 16:53:03",
    children: "",
    acceptChannelName: "",
    eventName: "Modify Subscriber",
    offerId: 4,
    accNbr: "73007362",
    bundleMemAlias: "",
    custOrderId: 121219640,
    orderStateName: "Completion",
  },
  {
    orderType: "B",
    subsPlanName: "SC_1000_Prepaid_Reguler",
    orderNbr: "2025110421177663",
    offerName: "Telkomcel Prepaid Channel",
    // routingId: "",
    orderItemId: 121177663,
    completedDate: "2025-11-04 16:47:44",
    orderState: "C",
    contactChannelId: 1,
    offerType: "2",
    subsEventId: 189,
    createdMan: "IT Center Administrator - admin",
    contactChannelName: "Point of Sale",
    createdDate: "2025-11-04 16:46:58",
    children: "",
    acceptChannelName: "",
    eventName: "Modify Subscriber",
    offerId: 4,
    accNbr: "73007362",
    bundleMemAlias: "",
    custOrderId: 121219639,
    orderStateName: "Completion",
  },
  {
    orderType: "B",
    subsPlanName: "SC_1000_Prepaid_Reguler",
    orderNbr: "2025103021177590",
    offerName: "Telkomcel Prepaid Channel",
    // routingId: "",
    orderItemId: 121177590,
    completedDate: "2025-10-30 21:39:30",
    orderState: "C",
    contactChannelId: 1,
    offerType: "2",
    subsEventId: 189,
    createdMan: "IT Center Administrator - admin",
    contactChannelName: "Point of Sale",
    createdDate: "2025-10-30 21:37:34",
    children: "",
    acceptChannelName: "",
    eventName: "Modify Subscriber",
    offerId: 4,
    accNbr: "73007362",
    bundleMemAlias: "",
    custOrderId: 121219633,
    orderStateName: "Completion",
  },
  {
    orderType: "B",
    subsPlanName: "SC_1000_Prepaid_Reguler",
    orderNbr: "2025103021177588",
    offerName: "Telkomcel Prepaid Channel",
    // routingId: "",
    orderItemId: 121177588,
    completedDate: "2025-10-30 21:26:40",
    orderState: "C",
    contactChannelId: 1,
    offerType: "2",
    subsEventId: 189,
    createdMan: "IT Center Administrator - admin",
    contactChannelName: "Point of Sale",
    createdDate: "2025-10-30 21:25:18",
    children: "",
    acceptChannelName: "",
    eventName: "Modify Subscriber",
    offerId: 4,
    accNbr: "73007362",
    bundleMemAlias: "",
    custOrderId: 121219631,
    orderStateName: "Completion",
  },
  {
    orderType: "B",
    subsPlanName: "SC_1000_Prepaid_Reguler",
    orderNbr: "2025103021177587",
    offerName: "Telkomcel Prepaid Channel",
    // routingId: "",
    orderItemId: 121177587,
    completedDate: "2025-10-30 21:24:15",
    orderState: "C",
    contactChannelId: 1,
    offerType: "2",
    subsEventId: 189,
    createdMan: "IT Center Administrator - admin",
    contactChannelName: "Point of Sale",
    createdDate: "2025-10-30 21:22:08",
    children: "",
    acceptChannelName: "",
    eventName: "Modify Subscriber",
    offerId: 4,
    accNbr: "73007362",
    bundleMemAlias: "",
    custOrderId: 121219630,
    orderStateName: "Completion",
  },
  {
    orderType: "B",
    subsPlanName: "SC_1000_Prepaid_Reguler",
    orderNbr: "2025103021177586",
    offerName: "Telkomcel Prepaid Channel",
    // routingId: "",
    orderItemId: 121177586,
    completedDate: "2025-10-30 21:17:55",
    orderState: "C",
    contactChannelId: 1,
    offerType: "2",
    subsEventId: 189,
    createdMan: "IT Center Administrator - admin",
    contactChannelName: "Point of Sale",
    createdDate: "2025-10-30 21:16:06",
    children: "",
    acceptChannelName: "",
    eventName: "Modify Subscriber",
    offerId: 4,
    accNbr: "73007362",
    bundleMemAlias: "",
    custOrderId: 121219629,
    orderStateName: "Completion",
  },
];

export const mockOrderState: orderState[] = [
  {
    comments: "����Order Intake",
    orderState: "I",
    orderStateName: "Order Intake",
  },
  {
    comments: "��������Order Decomposition",
    orderState: "D",
    orderStateName: "Order Decomposition",
  },
  {
    comments: "����Feasibility Check",
    orderState: "F",
    orderStateName: "Feasibility Check",
  },
  {
    comments: "��������/����Provisioning/Activation",
    orderState: "P",
    orderStateName: "Provisioning/Activation",
  },
  {
    comments: "����Completion",
    orderState: "C",
    orderStateName: "Completion",
  },
  {
    comments: "����Cancel",
    orderState: "E",
    orderStateName: "Cancel",
  },
  {
    comments: "������",
    orderState: "B",
    orderStateName: "Wait",
  },
  {
    comments: "����",
    orderState: "S",
    orderStateName: "Suspend",
  },
  {
    comments: "����",
    orderState: "G",
    orderStateName: "Exception",
  },
  {
    comments: "������������",
    orderState: "J",
    orderStateName: "Provisioning Error",
  },
  {
    comments: "������������",
    orderState: "W",
    orderStateName: "Waiting for manual review",
  },
];

export const mockSubsEvent: orderSubsEvent[] = [
  {
    subsEventId: "76",
    comments: "��������Join Organization",
    eventName: "(Gota) Join Organization",
    priority: "100",
  },
  {
    subsEventId: "77",
    comments: "��������Quit Organization",
    eventName: "(Gota) Quit Organization",
    priority: "100",
  },
  {
    subsEventId: "377",
    comments: "������������",
    eventName: "Abbrv Number  Management",
  },
  {
    subsEventId: "237",
    comments: "������������",
    eventName: "Active Individual Price Plan",
  },
  {
    subsEventId: "151",
    comments: "Active Related Product",
    eventName: "Active Related Product",
  },
  {
    subsEventId: "275",
    comments: "����������������������",
    eventName: "Active To InActive",
  },
  {
    subsEventId: "230",
    comments: "������������",
    eventName: "Add Abbrv Number",
  },
  {
    subsEventId: "84",
    comments: "Add Family Number������������",
    eventName: "Add Family Number",
    priority: "100",
  },
  {
    subsEventId: "285",
    comments: "Add One-off Charge",
    eventName: "Add One-off Charge",
  },
  {
    subsEventId: "81",
    comments: "������������Add Related Product",
    eventName: "Add Related Product",
    priority: "100",
  },
  {
    subsEventId: "516",
    comments: "All One-off Event",
    eventName: "All One-off Event",
    priority: "1",
  },
  {
    subsEventId: "427",
    comments: "��������������������������",
    eventName: "Automatic Re-contract",
  },
  {
    subsEventId: "555",
    comments: "Automatic Recharge",
    eventName: "Automatic Recharge",
  },
  {
    subsEventId: "352",
    comments: "����",
    eventName: "BALANCE ADJUST",
  },
];
