export const accmTypeDummyData = [
  {
    accumulationTypeId: 1,
    accumulationTypeName: "Accrual",
    mode: "ACC",
    mask: "###,###.##",
    unitType: "PERCENT",
    unitPrecision: 2,
    roundWay: "UP",
    precision: 2,
    measurementFeature: "data",
    remarks: "data",
  },
  {
    accumulationTypeId: 2,
    accumulationTypeName: "Cash Basis",
    mode: "CASH",
    mask: "###,###",
    unitType: null,
    unitPrecision: null,
    roundWay: "NEAREST",
    precision: 0,
    measurementFeature: "data",
    remarks: "data",
  },
  {
    accumulationTypeId: 3,
    accumulationTypeName: "Revenue Based",
    mode: "REV",
    mask: "###,###.###",
    unitType: "PERCENT",
    unitPrecision: 3,
    roundWay: "DOWN",
    precision: 3,
    measurementFeature: "data",
    remarks: "data",
  },
  {
    accumulationTypeId: 1,
    accumulationTypeName: "Accrual",
    mode: "ACC",
    mask: "###,###.##",
    unitType: "PERCENT",
    unitPrecision: 2,
    roundWay: "UP",
    precision: 2,
    measurementFeature: "data",
    remarks: "data",
  },
  {
    accumulationTypeId: 2,
    accumulationTypeName: "Cash Basis",
    mode: "CASH",
    mask: "###,###",
    unitType: null,
    unitPrecision: null,
    roundWay: "NEAREST",
    precision: 0,
    measurementFeature: "data",
    remarks: "data",
  },
  {
    accumulationTypeId: 3,
    accumulationTypeName: "Revenue Based",
    mode: "REV",
    mask: "###,###.###",
    unitType: "PERCENT",
    unitPrecision: 3,
    roundWay: "DOWN",
    precision: 3,
    measurementFeature: "data",
    remarks: "data",
  },
  {
    accumulationTypeId: 1,
    accumulationTypeName: "Accrual",
    mode: "ACC",
    mask: "###,###.##",
    unitType: "PERCENT",
    unitPrecision: 2,
    roundWay: "UP",
    precision: 2,
    measurementFeature: "data",
    remarks: "data",
  },
  {
    accumulationTypeId: 2,
    accumulationTypeName: "Cash Basis",
    mode: "CASH",
    mask: "###,###",
    unitType: null,
    unitPrecision: null,
    roundWay: "NEAREST",
    precision: 0,
    measurementFeature: "data",
    remarks: "data",
  },
  {
    accumulationTypeId: 3,
    accumulationTypeName: "Revenue Based",
    mode: "REV",
    mask: "###,###.###",
    unitType: "PERCENT",
    unitPrecision: 3,
    roundWay: "DOWN",
    precision: 3,
    measurementFeature: "data",
    remarks: "data",
  },
];

export const accmTypeDummyResponse = {
  status: 200,
  message: "Success",
  data: accmTypeDummyData,
  totalRows: accmTypeDummyData.length,
  totalPage: 1,
};

export const AccmCalculationDummy = [
  {
    id: "test",
    pricePlan: "testMade",
    price: "testArya",
    accumulationPeriod: "testMadeArya",
  },
  {
    id: "test",
    pricePlan: "testMade",
    price: "testArya",
    accumulationPeriod: "testMadeArya",
  },
  {
    id: "test",
    pricePlan: "testMade",
    price: "testArya",
    accumulationPeriod: "testMadeArya",
  },
  {
    id: "test",
    pricePlan: "testMade",
    price: "testArya",
    accumulationPeriod: "testMadeArya",
  },
  {
    id: "test",
    pricePlan: "testMade",
    price: "testArya",
    accumulationPeriod: "testMadeArya",
  },
  {
    id: "test",
    pricePlan: "testMade",
    price: "testArya",
    accumulationPeriod: "testMadeArya",
  },
  {
    id: "test",
    pricePlan: "testMade",
    price: "testArya",
    accumulationPeriod: "testMadeArya",
  },
  {
    id: "test",
    pricePlan: "testMade",
    price: "testArya",
    accumulationPeriod: "testMadeArya",
  },
];

export const AccmPrice = [
  {
    id: "test",
    pricePlan: "Raja Ganteng",
    price: "Explaner Idol",
    accumulationPrice: "king React",
  },
  {
    id: "test",
    pricePlan: "Raja Ganteng",
    price: "Explaner Idol",
    accumulationPrice: "king React",
  },
  {
    id: "test",
    pricePlan: "Raja Ganteng",
    price: "Explaner Idol",
    accumulationPrice: "king React",
  },
  {
    id: "test",
    pricePlan: "Raja Ganteng",
    price: "Explaner Idol",
    accumulationPrice: "king React",
  },
  {
    id: "test",
    pricePlan: "Raja Ganteng",
    price: "Explaner Idol",
    accumulationPrice: "king React",
  },
  {
    id: "test",
    pricePlan: "Raja Ganteng",
    price: "Explaner Idol",
    accumulationPrice: "king React",
  },
  {
    id: "test",
    pricePlan: "Raja Ganteng",
    price: "Explaner Idol",
    accumulationPrice: "king React",
  },
  {
    id: "test",
    pricePlan: "Raja Ganteng",
    price: "Explaner Idol",
    accumulationPrice: "king React",
  },
  {
    id: "test",
    pricePlan: "Raja Ganteng",
    price: "Explaner Idol",
    accumulationPrice: "king React",
  },
];
export const AccumulationDummy = [
  {
    id: "testTest",
    pricePlan: "test",
    ratePlan: "wahyuSiPetualang",
    event: "Wahyu EXPLANER idol STS ngasal aja karena ini dummy",
    validateDate: "12-12-2045",
    accumulationType: "ngetest doang",
  },
  {
    id: "testTest",
    pricePlan: "test",
    ratePlan: "wahyuSiPetualang",
    event: "Wahyu EXPLANER idol STS ngasal aja karena ini dummy",
    validateDate: "12-12-2045",
    accumulationType: "ngetest doang",
  },
  {
    id: "testTest",
    pricePlan: "test",
    ratePlan: "wahyuSiPetualang",
    event: "Wahyu EXPLANER idol STS ngasal aja karena ini dummy",
    validateDate: "12-12-2045",
    accumulationType: "ngetest doang",
  },
  {
    id: "testTest",
    pricePlan: "test",
    ratePlan: "wahyuSiPetualang",
    event: "Wahyu EXPLANER idol STS ngasal aja karena ini dummy",
    validateDate: "12-12-2045",
    accumulationType: "ngetest doang",
  },
  {
    id: "testTest",
    pricePlan: "test",
    ratePlan: "wahyuSiPetualang",
    event: "Wahyu EXPLANER idol STS ngasal aja karena ini dummy",
    validateDate: "12-12-2045",
    accumulationType: "ngetest doang",
  },
  {
    id: "testTest",
    pricePlan: "test",
    ratePlan: "wahyuSiPetualang",
    event: "Wahyu EXPLANER idol STS ngasal aja karena ini dummy",
    validateDate: "12-12-2045",
    accumulationType: "ngetest doang",
  },
];
export const AccmTriggDummy = [
  {
    id: "test",
    accumulationPrice: "test L A G I",
    validateDate: "Waduuuuuuuuuuuuuuuuuuuuuuuuuuh",
  },
  {
    id: "test",
    accumulationPrice: "test L A G I",
    validateDate: "Waduuuuuuuuuuuuuuuuuuuuuuuuuuh",
  },
  {
    id: "test",
    accumulationPrice: "test L A G I",
    validateDate: "Waduuuuuuuuuuuuuuuuuuuuuuuuuuh",
  },
  {
    id: "test",
    accumulationPrice: "test L A G I",
    validateDate: "Waduuuuuuuuuuuuuuuuuuuuuuuuuuh",
  },
  {
    id: "test",
    accumulationPrice: "test L A G I",
    validateDate: "Waduuuuuuuuuuuuuuuuuuuuuuuuuuh",
  },
  {
    id: "test",
    accumulationPrice: "test L A G I",
    validateDate: "Waduuuuuuuuuuuuuuuuuuuuuuuuuuh",
  },
  {
    id: "test",
    accumulationPrice: "test L A G I",
    validateDate: "Waduuuuuuuuuuuuuuuuuuuuuuuuuuh",
  },
  {
    id: "test",
    accumulationPrice: "test L A G I",
    validateDate: "Waduuuuuuuuuuuuuuuuuuuuuuuuuuh",
  },
];
