import { queryTempTable } from "@/pages/main-menu/preNewConnnection/interface";

export interface OfferDetail {
  cycleQuantity?: string;
  saleListPrice?: number;
  expDate?: string;
  expTimeUnit?: string;
  offerType?: string;
  effDate?: string;
  effType?: string;
  agreementEffType?: string;
  salePriceGstType?: string;
  state?: string;
  timeUnit?: string;
  comments?: string;
  offerName?: string;
  prodType?: string;
  spId?: string;
  rentPriceGstType?: string;
  rentListPrice?: number;
  createdDate?: string;
  offerCode?: string;
  autoContinueFlag?: string;
  offerId?: string;
  duplicateFlag?: string;
  expOff?: string;
  stateDate?: string;
  specTime?: string;
}

export interface ModSubsServiceChild {
  agreementPeriod?: string;
  relAgmUnit?: string;
  groupType?: string;
  modelId?: string;
  expTimeUnit?: string;
  offerGroupName?: string;
  relAgmOffset?: string;
  offer?: OfferDetail;
  relExpOffset?: string;
  offerType: string;
  children?: string;
  effType?: string;
  parentOfferGroupId?: number; // ends with Id
  offerGroupId?: number; // ends with Id
  servType?: string;
  id: number; // ends with Id
  isDummyEsn?: string;
  seq?: string;
  timeUnit?: string;
  defaultFlag?: string;
  offerName: string;
  necessary?: string;
  stockType?: string;
  parentOfferPagId?: number; // ends with Id
  lowerLimit?: string;
  parentId?: number; // ends with Id
  defaultPricePlan?: boolean;
  offerGroupMemId?: number; // ends with Id
  relExpUnit?: string;
  offerCode?: string;
  name?: string;
  offerId: number; // ends with Id
  duplicateFlag?: string;
  expOff?: string;
  upperLimit?: string;
  offerGroupType?: string;
  offerDto?: SubserviceOfferDto;
  isDuplicate?: string;
}

export interface SubserviceOfferDto {
  offerId: string;
  offerType: string;
  offerName: string; //"Prepaid_Reguler_DPP";
  comments?: string; //null;
  offerCode: string; //"DP_1000";
  saleListPrice: 0;
  rentListPrice: 0;
  effDate: string; //null;
  expDate: string; //null;
  createdDate: string; // null;
  state: string; //"A";
  stateDate: string; //null;
  effType: string; //"B";
  specTime: string; //null;
  autoContinueFlag: string; //"N";
  cycleQuantity: string; //null;
  timeUnit: string; //null;
  duplicateFlag: string; //null;
  spId: 0;
  expOff: string; //null;
  expTimeUnit: string; //null;
  agreementEffType: string; //null;
  salePriceGstType: string; //null;
  rentPriceGstType: string; //null;
  prodType: string; //null;
  childOfferGroupId: string; //null;
  defaultEffType: string; //"B";
}

export interface ModSubsService {
  agreementPeriod?: string;
  relAgmUnit?: string;
  groupType?: string;
  modelId?: string;
  expTimeUnit?: string;
  offerGroupName?: string;
  relAgmOffset?: string;
  offer?: string;
  relExpOffset?: string;
  offerType?: string;
  children?: ModSubsServiceChild[];
  effType?: string;
  parentOfferGroupId?: number; // ends with Id
  offerGroupId?: number; // ends with Id
  servType?: string;
  id?: number; // ends with Id
  isDummyEsn?: string;
  seq?: string;
  timeUnit?: string;
  defaultFlag?: string;
  offerName?: string;
  necessary?: string;
  stockType?: string;
  parentOfferPagId?: number; // ends with Id
  lowerLimit?: string;
  parentId?: number; // ends with Id
  defaultPricePlan?: boolean;
  offerGroupMemId?: number; // ends with Id
  relExpUnit?: string;
  offerCode?: string;
  name?: string;
  offerId?: number; // ends with Id
  duplicateFlag?: string;
  expOff?: string;
  upperLimit?: string;
  offerGroupType?: string;
}

export const mockModSubs: ModSubsService[] = [
  {
    agreementPeriod: "",
    relAgmUnit: "",
    groupType: "C",
    modelId: "",
    expTimeUnit: "",
    offerGroupName: "SMS Price Plan Group",
    relAgmOffset: "",
    offer: "",
    relExpOffset: "",
    offerType: "",
    children: [
      {
        agreementPeriod: "",
        relAgmUnit: "",
        groupType: "",
        modelId: "",
        expTimeUnit: "D",
        offerGroupName: "",
        relAgmOffset: "",
        offer: {
          cycleQuantity: "",
          saleListPrice: 0,
          expDate: "",
          expTimeUnit: "D",
          offerType: "4",
          effDate: "2023/07/26 00:00:00",
          effType: "B",
          agreementEffType: "",
          salePriceGstType: "",
          state: "A",
          timeUnit: "",
          comments: "",
          offerName: "SMS Combo 65 SSU",
          prodType: "",
          spId: "0",
          rentPriceGstType: "",
          rentListPrice: 0,
          createdDate: "2023/07/26 11:41:23",
          offerCode: "sC65",
          autoContinueFlag: "Y",
          offerId: "209",
          duplicateFlag: "C",
          expOff: "7",
          stateDate: "2023/07/26 11:41:23",
          specTime: "",
        },
        relExpOffset: "7",
        offerType: "4",
        children: "",
        effType: "B",
        parentOfferGroupId: 20,
        // offerGroupId: "",
        servType: "",
        id: 209,
        isDummyEsn: "",
        seq: "4",
        timeUnit: "",
        defaultFlag: "N",
        offerName: "SMS Combo 65 SSU",
        necessary: "",
        stockType: "",
        // parentOfferPagId: "",
        lowerLimit: "",
        parentId: 20,
        defaultPricePlan: false,
        offerGroupMemId: 804,
        relExpUnit: "D",
        offerCode: "sC65",
        name: "SMS Combo 65 SSU",
        offerId: 209,
        duplicateFlag: "C",
        expOff: "7",
        upperLimit: "",
        offerGroupType: "",
      },
      {
        agreementPeriod: "",
        relAgmUnit: "",
        groupType: "",
        modelId: "",
        expTimeUnit: "D",
        offerGroupName: "",
        relAgmOffset: "",
        offer: {
          cycleQuantity: "",
          saleListPrice: 0,
          expDate: "",
          expTimeUnit: "D",
          offerType: "4",
          effDate: "2023/07/26 00:00:00",
          effType: "B",
          agreementEffType: "",
          salePriceGstType: "",
          state: "A",
          timeUnit: "",
          comments: "",
          offerName: "SMS Combo 130 SSU",
          prodType: "",
          spId: "0",
          rentPriceGstType: "",
          rentListPrice: 0,
          createdDate: "2023/07/26 11:41:23",
          offerCode: "sC13",
          autoContinueFlag: "Y",
          offerId: "206",
          duplicateFlag: "C",
          expOff: "30",
          stateDate: "2023/07/26 11:41:23",
          specTime: "",
        },
        relExpOffset: "30",
        offerType: "4",
        children: "",
        effType: "B",
        parentOfferGroupId: 20,
        // offerGroupId: "",
        servType: "",
        id: 206,
        isDummyEsn: "",
        seq: "1",
        timeUnit: "",
        defaultFlag: "N",
        offerName: "SMS Combo 130 SSU",
        necessary: "",
        stockType: "",
        // parentOfferPagId: "",
        lowerLimit: "",
        parentId: 20,
        defaultPricePlan: false,
        offerGroupMemId: 801,
        relExpUnit: "D",
        offerCode: "sC13",
        name: "SMS Combo 130 SSU",
        offerId: 206,
        duplicateFlag: "C",
        expOff: "30",
        upperLimit: "",
        offerGroupType: "",
      },
      {
        agreementPeriod: "",
        relAgmUnit: "",
        groupType: "",
        modelId: "",
        expTimeUnit: "D",
        offerGroupName: "",
        relAgmOffset: "",
        offer: {
          cycleQuantity: "",
          saleListPrice: 0,
          expDate: "",
          expTimeUnit: "D",
          offerType: "4",
          effDate: "2023/07/26 00:00:00",
          effType: "B",
          agreementEffType: "",
          salePriceGstType: "",
          state: "A",
          timeUnit: "",
          comments: "",
          offerName: "SMS Combo 20 SSU",
          prodType: "",
          spId: "0",
          rentPriceGstType: "",
          rentListPrice: 0,
          createdDate: "2023/07/26 11:41:23",
          offerCode: "sC20",
          autoContinueFlag: "Y",
          offerId: "207",
          duplicateFlag: "C",
          expOff: "3",
          stateDate: "2023/07/26 11:41:23",
          specTime: "",
        },
        relExpOffset: "3",
        offerType: "4",
        children: "",
        effType: "B",
        parentOfferGroupId: 20,
        // offerGroupId: "",
        servType: "",
        id: 207,
        isDummyEsn: "",
        seq: "2",
        timeUnit: "",
        defaultFlag: "N",
        offerName: "SMS Combo 20 SSU",
        necessary: "",
        stockType: "",
        // parentOfferPagId: "",
        lowerLimit: "",
        parentId: 20,
        defaultPricePlan: false,
        offerGroupMemId: 802,
        relExpUnit: "D",
        offerCode: "sC20",
        name: "SMS Combo 20 SSU",
        offerId: 207,
        duplicateFlag: "C",
        expOff: "3",
        upperLimit: "",
        offerGroupType: "",
      },
      {
        agreementPeriod: "",
        relAgmUnit: "",
        groupType: "",
        modelId: "",
        expTimeUnit: "D",
        offerGroupName: "",
        relAgmOffset: "",
        offer: {
          cycleQuantity: "",
          saleListPrice: 0,
          expDate: "",
          expTimeUnit: "D",
          offerType: "4",
          effDate: "2023/07/26 00:00:00",
          effType: "B",
          agreementEffType: "",
          salePriceGstType: "",
          state: "A",
          timeUnit: "",
          comments: "F10",
          offerName: "F10 New: 10 SMS on-net + 500 MB internet",
          prodType: "",
          spId: "0",
          rentPriceGstType: "",
          rentListPrice: 0,
          createdDate: "2023/07/26 11:41:23",
          offerCode: "F10",
          autoContinueFlag: "N",
          offerId: "205",
          duplicateFlag: "C",
          expOff: "1",
          stateDate: "2023/07/26 11:41:23",
          specTime: "",
        },
        relExpOffset: "1",
        offerType: "4",
        children: "",
        effType: "B",
        parentOfferGroupId: 20,
        // offerGroupId: "",
        servType: "",
        id: 205,
        isDummyEsn: "",
        seq: "5",
        timeUnit: "",
        defaultFlag: "N",
        offerName: "F10 New: 10 SMS on-net + 500 MB internet",
        necessary: "",
        stockType: "",
        // parentOfferPagId: "",
        lowerLimit: "",
        parentId: 20,
        defaultPricePlan: false,
        offerGroupMemId: 805,
        relExpUnit: "D",
        offerCode: "F10",
        name: "F10 New: 10 SMS on-net + 500 MB internet",
        offerId: 205,
        duplicateFlag: "C",
        expOff: "1",
        upperLimit: "",
        offerGroupType: "",
      },
      {
        agreementPeriod: "",
        relAgmUnit: "",
        groupType: "",
        modelId: "",
        expTimeUnit: "D",
        offerGroupName: "",
        relAgmOffset: "",
        offer: {
          cycleQuantity: "",
          saleListPrice: 0,
          expDate: "",
          expTimeUnit: "D",
          offerType: "4",
          effDate: "2023/07/26 00:00:00",
          effType: "B",
          agreementEffType: "",
          salePriceGstType: "",
          state: "A",
          timeUnit: "",
          comments: "",
          offerName: "SMS Combo 5 SSU",
          prodType: "",
          spId: "0",
          rentPriceGstType: "",
          rentListPrice: 0,
          createdDate: "2023/07/26 11:41:23",
          offerCode: "sC10",
          autoContinueFlag: "Y",
          offerId: "208",
          duplicateFlag: "C",
          expOff: "1",
          stateDate: "2023/07/26 11:41:23",
          specTime: "",
        },
        relExpOffset: "1",
        offerType: "4",
        children: "",
        effType: "B",
        parentOfferGroupId: 20,
        // offerGroupId: "",
        servType: "",
        id: 208,
        isDummyEsn: "",
        seq: "3",
        timeUnit: "",
        defaultFlag: "N",
        offerName: "SMS Combo 5 SSU",
        necessary: "",
        stockType: "",
        // parentOfferPagId: "",
        lowerLimit: "",
        parentId: 20,
        defaultPricePlan: false,
        offerGroupMemId: 803,
        relExpUnit: "D",
        offerCode: "sC10",
        name: "SMS Combo 5 SSU",
        offerId: 208,
        duplicateFlag: "C",
        expOff: "1",
        upperLimit: "",
        offerGroupType: "",
      },
    ],
    effType: "",
    // parentOfferGroupId: "",
    offerGroupId: 20,
    servType: "",
    id: 20,
    isDummyEsn: "",
    seq: "151",
    timeUnit: "",
    defaultFlag: "",
    offerName: "",
    necessary: "0",
    stockType: "",
    // parentOfferPagId: "",
    lowerLimit: "",
    // parentId: "",
    defaultPricePlan: false,
    // offerGroupMemId: "",
    relExpUnit: "",
    offerCode: "",
    name: "SMS Price Plan Group",
    // offerId: "",
    duplicateFlag: "",
    expOff: "",
    upperLimit: "",
    offerGroupType: "4",
  },
  {
    agreementPeriod: "",
    relAgmUnit: "",
    groupType: "B",
    modelId: "",
    expTimeUnit: "",
    offerGroupName: "SC_1000_Prepaid_Reguler",
    relAgmOffset: "",
    offer: "",
    relExpOffset: "",
    offerType: "",
    children: [
      {
        agreementPeriod: "",
        relAgmUnit: "",
        groupType: "",
        modelId: "",
        expTimeUnit: "",
        offerGroupName: "",
        relAgmOffset: "",
        offer: {
          cycleQuantity: "",
          saleListPrice: 0,
          expDate: "",
          expTimeUnit: "",
          offerType: "4",
          effDate: "2023/07/26 00:00:00",
          effType: "B",
          agreementEffType: "",
          salePriceGstType: "",
          state: "A",
          timeUnit: "",
          comments: "",
          offerName: "Prepaid_Reguler_DPP",
          prodType: "",
          spId: "0",
          rentPriceGstType: "",
          rentListPrice: 0,
          createdDate: "2023/07/26 11:41:18",
          offerCode: "DP_1000",
          autoContinueFlag: "N",
          offerId: "79",
          duplicateFlag: "",
          expOff: "",
          stateDate: "2023/07/26 11:41:18",
          specTime: "",
        },
        relExpOffset: "",
        offerType: "4",
        children: "",
        effType: "B",
        parentOfferGroupId: 26,
        // offerGroupId: "",
        servType: "",
        id: 79,
        isDummyEsn: "",
        seq: "1",
        timeUnit: "",
        defaultFlag: "Y",
        offerName: "Prepaid_Reguler_DPP",
        necessary: "",
        stockType: "",
        // parentOfferPagId: "",
        lowerLimit: "",
        parentId: 26,
        defaultPricePlan: true,
        offerGroupMemId: 659,
        relExpUnit: "",
        offerCode: "DP_1000",
        name: "Prepaid_Reguler_DPP",
        offerId: 79,
        duplicateFlag: "",
        expOff: "",
        upperLimit: "",
        offerGroupType: "",
      },
    ],
    effType: "",
    // parentOfferGroupId: "",
    offerGroupId: 26,
    servType: "",
    id: 26,
    isDummyEsn: "",
    seq: "6",
    timeUnit: "",
    defaultFlag: "",
    offerName: "",
    necessary: "1",
    stockType: "",
    // parentOfferPagId: "",
    lowerLimit: "",
    // parentId: "",
    defaultPricePlan: true,
    // offerGroupMemId: "",
    relExpUnit: "",
    offerCode: "",
    name: "SC_1000_Prepaid_Reguler",
    // offerId: "",
    duplicateFlag: "",
    expOff: "",
    upperLimit: "",
    offerGroupType: "6",
  },
];

export const mockModSubsHave: ModSubsService[] = [
  {
    agreementPeriod: "",
    relAgmUnit: "",
    groupType: "C",
    modelId: "",
    expTimeUnit: "",
    offerGroupName: "SMS Price Plan Group",
    relAgmOffset: "",
    offer: "",
    relExpOffset: "",
    offerType: "",
    children: [
      {
        agreementPeriod: "",
        relAgmUnit: "",
        groupType: "",
        modelId: "",
        expTimeUnit: "D",
        offerGroupName: "",
        relAgmOffset: "",
        offer: {
          cycleQuantity: "",
          saleListPrice: 0,
          expDate: "",
          expTimeUnit: "D",
          offerType: "4",
          effDate: "2023/07/26 00:00:00",
          effType: "B",
          agreementEffType: "",
          salePriceGstType: "",
          state: "A",
          timeUnit: "",
          comments: "",
          offerName: "SMS Combo 65 SSU",
          prodType: "",
          spId: "0",
          rentPriceGstType: "",
          rentListPrice: 0,
          createdDate: "2023/07/26 11:41:23",
          offerCode: "sC65",
          autoContinueFlag: "Y",
          offerId: "209",
          duplicateFlag: "C",
          expOff: "7",
          stateDate: "2023/07/26 11:41:23",
          specTime: "",
        },
        relExpOffset: "7",
        offerType: "4",
        children: "",
        effType: "B",
        parentOfferGroupId: 20,
        // offerGroupId: "",
        servType: "",
        id: 209,
        isDummyEsn: "",
        seq: "4",
        timeUnit: "",
        defaultFlag: "N",
        offerName: "SMS Combo 65 SSU",
        necessary: "",
        stockType: "",
        // parentOfferPagId: "",
        lowerLimit: "",
        parentId: 20,
        defaultPricePlan: false,
        offerGroupMemId: 804,
        relExpUnit: "D",
        offerCode: "sC65",
        name: "SMS Combo 65 SSU",
        offerId: 209,
        duplicateFlag: "C",
        expOff: "7",
        upperLimit: "",
        offerGroupType: "",
      },
    ],
    effType: "",
    // parentOfferGroupId: "",
    offerGroupId: 20,
    servType: "",
    id: 20,
    isDummyEsn: "",
    seq: "151",
    timeUnit: "",
    defaultFlag: "",
    offerName: "",
    necessary: "0",
    stockType: "",
    // parentOfferPagId: "",
    lowerLimit: "",
    // parentId: "",
    defaultPricePlan: false,
    // offerGroupMemId: "",
    relExpUnit: "",
    offerCode: "",
    name: "SMS Price Plan Group",
    // offerId: "",
    duplicateFlag: "",
    expOff: "",
    upperLimit: "",
    offerGroupType: "4",
  },
  {
    agreementPeriod: "",
    relAgmUnit: "",
    groupType: "B",
    modelId: "",
    expTimeUnit: "",
    offerGroupName: "SC_1000_Prepaid_Reguler",
    relAgmOffset: "",
    offer: "",
    relExpOffset: "",
    offerType: "",
    children: [
      {
        agreementPeriod: "",
        relAgmUnit: "",
        groupType: "",
        modelId: "",
        expTimeUnit: "",
        offerGroupName: "",
        relAgmOffset: "",
        offer: {
          cycleQuantity: "",
          saleListPrice: 0,
          expDate: "",
          expTimeUnit: "",
          offerType: "4",
          effDate: "2023/07/26 00:00:00",
          effType: "B",
          agreementEffType: "",
          salePriceGstType: "",
          state: "A",
          timeUnit: "",
          comments: "",
          offerName: "Prepaid_Reguler_DPP",
          prodType: "",
          spId: "0",
          rentPriceGstType: "",
          rentListPrice: 0,
          createdDate: "2023/07/26 11:41:18",
          offerCode: "DP_1000",
          autoContinueFlag: "N",
          offerId: "79",
          duplicateFlag: "",
          expOff: "",
          stateDate: "2023/07/26 11:41:18",
          specTime: "",
        },
        relExpOffset: "",
        offerType: "4",
        children: "",
        effType: "B",
        parentOfferGroupId: 26,
        // offerGroupId: "",
        servType: "",
        id: 79,
        isDummyEsn: "",
        seq: "1",
        timeUnit: "",
        defaultFlag: "Y",
        offerName: "Prepaid_Reguler_DPP",
        necessary: "",
        stockType: "",
        // parentOfferPagId: "",
        lowerLimit: "",
        parentId: 26,
        defaultPricePlan: true,
        offerGroupMemId: 659,
        relExpUnit: "",
        offerCode: "DP_1000",
        name: "Prepaid_Reguler_DPP",
        offerId: 79,
        duplicateFlag: "",
        expOff: "",
        upperLimit: "",
        offerGroupType: "",
      },
    ],
    effType: "",
    // parentOfferGroupId: "",
    offerGroupId: 26,
    servType: "",
    id: 26,
    isDummyEsn: "",
    seq: "6",
    timeUnit: "",
    defaultFlag: "",
    offerName: "",
    necessary: "1",
    stockType: "",
    // parentOfferPagId: "",
    lowerLimit: "",
    // parentId: "",
    defaultPricePlan: true,
    // offerGroupMemId: "",
    relExpUnit: "",
    offerCode: "",
    name: "SC_1000_Prepaid_Reguler",
    // offerId: "",
    duplicateFlag: "",
    expOff: "",
    upperLimit: "",
    offerGroupType: "6",
  },
];

const mockOfferData = {
  boAccessName: "custOrder",
  commonDataId: "d90IH3UdKE3I4mDA2MdA17IA4lWfkZeW",
  dirtyList: [
    {
      action: "OVERRIDE",
      bo: false,
      boAccessName: "custOrder",
      filters: {},
      flushed: false,
      isRoot: "Y",
      location: {
        accessNamePath: "/",
        array: false,
        bo: true,
        dataType: "BO",
        includeObjectId: "2f20e016-f047-4677-abe6-7df4b370f121",
        itemAccessName: "custOrder",
        itemType: "VI",
        parentArray: false,
      },
      value: {
        SERV_TYPE: "15",
        CUST_ID: 120265000,
        CREATED_DATE: "2025-12-03 23:19:12",
        SP_ID: 0,
        ACCEPT_DATE: "2025-12-03 23:19:12",
        CUST_ORDER_ID: 121219848,
        ROUTING_ID: 1,
        OFFER_ID: "4",
        POS_SALE_MODE: 1,
        CONTACT_CHANNEL_ID: 1,
        A_PARTY_CODE: "120265000",
        ORDER_ITEM: [
          {
            SERV_TYPE: 15,
            DP_OFFER_ORDER: [
              {
                SERV_TYPE: 386,
                SP_ID: 0,
                ABS_EFF_DATE: "2025-09-26 16:28:29",
                OFFER_TYPE: "3",
                OFFER_NAME: "Incoming SMS",
                OFFER_ID: 74,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "3458ce2b-9737-46a0-b52b-49c7a412dd36",
                OLD_EFF_DATE: "2025-09-26 16:28:29",
                OFFER_INST_ID: 121308009,
                ORDER_ITEM_ID: 121178277,
              },
              {
                SERV_TYPE: 385,
                SP_ID: 0,
                ABS_EFF_DATE: "2025-09-26 16:28:29",
                OFFER_TYPE: "3",
                OFFER_NAME: "Outgoing SMS",
                OFFER_ID: 75,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "f8faad25-acad-4f0b-832c-3410645b2de9",
                OLD_EFF_DATE: "2025-09-26 16:28:29",
                OFFER_INST_ID: 121308010,
                ORDER_ITEM_ID: 121178277,
              },
              {
                SERV_TYPE: 138,
                SP_ID: 0,
                ABS_EFF_DATE: "2025-09-26 16:28:29",
                OFFER_TYPE: "3",
                OFFER_NAME: "Voice Service",
                OFFER_ID: 72,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "77faf8cb-ed9c-4ff7-a4ce-0ec8d63c6507",
                OLD_EFF_DATE: "2025-09-26 16:28:29",
                OFFER_INST_ID: 121308011,
                ORDER_ITEM_ID: 121178277,
              },
              {
                SERV_TYPE: 139,
                SP_ID: 0,
                ABS_EFF_DATE: "2025-09-26 16:28:29",
                OFFER_TYPE: "3",
                OFFER_NAME: "Data Service",
                OFFER_ID: 73,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "cd51cfe5-1b12-4810-87d5-a85e26d2c06a",
                OLD_EFF_DATE: "2025-09-26 16:28:29",
                OFFER_INST_ID: 121308012,
                ORDER_ITEM_ID: 121178277,
              },
              {
                TIMER_EVENT_ID: 1921,
                DP_OFFER_ORDER_ATTR: [
                  {
                    ATTR_VALUE: "1",
                    OFFER_ID: 213,
                    ATTR_ID: 624,
                    OPERATION_TYPE: "X",
                  },
                  {
                    ATTR_VALUE: "1",
                    OFFER_ID: 213,
                    ATTR_ID: 400003,
                    OPERATION_TYPE: "X",
                  },
                  {
                    ATTR_VALUE: "0",
                    OFFER_ID: 213,
                    ATTR_ID: 400004,
                    OPERATION_TYPE: "X",
                  },
                ],
                OLD_RESERVE_DATE: "2025-11-26 17:02:06",
                OFFER_ID: 213,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "81a9c36d-fc4f-427f-b563-81a5a1fdb05d",
                RESERVE_DATE: "2025-11-26 17:02:06",
                REL_EXP_UNIT: "D",
                REL_EXP_OFFSET: 3,
                DUPLICATE_FLAG: "B",
              },
              {
                TIMER_EVENT_ID: 1941,
                OLD_RESERVE_DATE: "2025-12-03 17:02:06",
                OFFER_ID: 1001,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "0c8e0372-697f-41b9-8739-e16b2f1a4933",
                RESERVE_DATE: "2025-12-03 17:02:06",
                REL_EXP_UNIT: "",
                DUPLICATE_FLAG: "",
              },
              {
                TIMER_EVENT_ID: 1942,
                DP_OFFER_ORDER_ATTR: [
                  {
                    ATTR_VALUE: "1",
                    OFFER_ID: 213,
                    ATTR_ID: 624,
                    OPERATION_TYPE: "X",
                  },
                  {
                    ATTR_VALUE: "1",
                    OFFER_ID: 213,
                    ATTR_ID: 400003,
                    OPERATION_TYPE: "X",
                  },
                  {
                    ATTR_VALUE: "0",
                    OFFER_ID: 213,
                    ATTR_ID: 400004,
                    OPERATION_TYPE: "X",
                  },
                ],
                OLD_RESERVE_DATE: "2025-12-03 17:02:06",
                OFFER_ID: 213,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "61fcc965-9cef-4818-b23d-25a191df52d7",
                RESERVE_DATE: "2025-12-03 17:02:06",
                REL_EXP_UNIT: "D",
                REL_EXP_OFFSET: 3,
                DUPLICATE_FLAG: "B",
              },
            ],
            ACCT: {
              PAYMENT_METHOD_ID: 1,
              CUST_ID: 120265000,
              ROUTING_ID: 1,
              ACCT_ID: 120255000,
              STATE: "A",
              BILLING_CYCLE_TYPE_ID: 1,
              DELIVER_METHOD: "",
              PAYMENT_TYPE: "A",
              DEFAULT_FLAG: "N",
              PARTY_TYPE: "A",
              ACCT_NBR: "930255000",
              POSTPAID: "N",
              PARTY_CODE: "1",
            },
            SUBS_PLAN_NAME: "SC_1000_Prepaid_Reguler",
            CUST_ORDER_ID: 121219848,
            OFFER_ID: 4,
            CONTACT_CHANNEL_ID: 1,
            IS_CHECK_OWE_CHARGE: true,
            SUBS_EVENT_ID: 189,
            ORDER_NBR: "2025120321178277",
            ACCT_ID: 120255000,
            IS_RESERVE: true,
            ORDER_TYPE: "B",
            OPERATION_TYPE: "A",
            SUBS_PLAN_ID: 360,
            CUST_ID: 120265000,
            SP_ID: 0,
            STATE_DATE: "2025-12-03 23:19:12",
            ORDER_STATE: "I",
            POS_SALE_MODE: 1,
            PREFIX: "670",
            IS_SAVED: true,
            POSTPAID: "N",
            PROD_STATE: "A",
            BLOCK_REASON: "00000000000000",
            SUBS_ID: 121308008,
            BESP_ADDRESS: "2025-12-04 21:20:18",
            OFFER_NAME: "Telkomcel Prepaid Channel",
            ACC_NBR: "73007362",
            ORDER_ITEM_ID: 121178277,
            CUST_NAME: "Development Test",
          },
        ],
        CUST: {
          CUST_ID: 120265000,
          ROUTING_ID: 1,
          CUST_TYPE: "A",
          CUST_CODE: "1120265000",
          CERT_ID: 120011000,
          CUST_NAME: "Development Test",
        },
        SUBS_EVENT_ID: 189,
        CUST_CONTACT: {
          CUST_ID: 120265000,
          CREATED_DATE: "2025-12-03 23:19:12",
          SP_ID: 0,
          PARTY_TYPE: "A",
          CUST_CONTACT_ID: 187456648,
          CONTACT_TYPE: "A",
          CONTACT_CHANNEL_ID: 1,
          RELA_ID: 121219848,
          CONTACT_EVENT_ID: "A",
          PARTY_CODE: "1",
        },
        PARTY_TYPE: "A",
        SEND_PROVISIONING_FLAG: "Y",
        CUST_ORDER_NBR: "121219848",
        CREDIT_LIMIT_MODE: "0",
        A_PARTY_TYPE: "D",
        STAFF_INFO: { AREA_ID: 1, ORG_ID: 1, STAFF_ID: 1, STAFF_JOB_ID: 1 },
        PARTY_CODE: "1",
      },
      valueType: "VI",
    },
  ],
  dsi: {},
  errors: [],
  hints: [],
  rollbackList: [],
  wizardPage: {
    accessName:
      "com.ztesoft.zsmart.bss.cc.orderentry.products.view.PreviewWindow",
    accessPath:
      "customercare/sharepage/flowpage/orderentry/PreviewWindowPage.swf",
    canBackward: true,
    canForward: true,
    code: "OrderInformationPreview",
    id: "OrderInformationPreview",
    properties: {},
  },
};

const mockSelectedOfferData = {
  boAccessName: "custOrder",
  commonDataId: "lweHZC6K9ARc9gT1aqL80625EOFXvtnP",
  dirtyList: [
    {
      action: "OVERRIDE",
      bo: false,
      boAccessName: "custOrder",
      filters: {},
      flushed: false,
      isRoot: "Y",
      location: {
        accessNamePath: "/",
        array: false,
        bo: true,
        dataType: "BO",
        includeObjectId: "2f20e016-f047-4677-abe6-7df4b370f121",
        itemAccessName: "custOrder",
        itemType: "VI",
        parentArray: false,
      },
      value: {
        SERV_TYPE: "15",
        CUST_ID: 120265000,
        CREATED_DATE: "2025-12-03 23:47:43",
        SP_ID: 0,
        ACCEPT_DATE: "2025-12-03 23:47:43",
        CUST_ORDER_ID: 121219849,
        ROUTING_ID: 1,
        OFFER_ID: "4",
        POS_SALE_MODE: 1,
        CONTACT_CHANNEL_ID: 1,
        A_PARTY_CODE: "120265000",
        ORDER_ITEM: [
          {
            SERV_TYPE: 15,
            DP_OFFER_ORDER: [
              {
                SERV_TYPE: 386,
                SP_ID: 0,
                ABS_EFF_DATE: "2025-09-26 16:28:29",
                OFFER_TYPE: "3",
                EFF_TYPE: "B",
                OFFER_NAME: "Incoming SMS",
                OFFER_ID: 74,
                OPERATION_TYPE: "M",
                OFFER_SEQ: "fa1d9ab6-f59c-41ad-a194-2a6ba0359047",
                RESERVE_DATE: "2025-12-05 17:02:06",
                OLD_EFF_DATE: "2025-09-26 16:28:29",
                REL_EXP_UNIT: "D",
                OFFER_INST_ID: 121308009,
                REL_EXP_OFFSET: "1",
                ORDER_ITEM_ID: 121178278,
              },
              {
                SERV_TYPE: 385,
                SP_ID: 0,
                ABS_EFF_DATE: "2025-09-26 16:28:29",
                OFFER_TYPE: "3",
                OFFER_NAME: "Outgoing SMS",
                OFFER_ID: 75,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "53c75215-24b4-49dd-8f2d-ab42e2ff6fc1",
                OLD_EFF_DATE: "2025-09-26 16:28:29",
                OFFER_INST_ID: 121308010,
                ORDER_ITEM_ID: 121178278,
              },
              {
                SERV_TYPE: 138,
                SP_ID: 0,
                ABS_EFF_DATE: "2025-09-26 16:28:29",
                OFFER_TYPE: "3",
                OFFER_NAME: "Voice Service",
                OFFER_ID: 72,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "0703b275-621f-4988-9198-4a1910b7354a",
                OLD_EFF_DATE: "2025-09-26 16:28:29",
                OFFER_INST_ID: 121308011,
                ORDER_ITEM_ID: 121178278,
              },
              {
                SERV_TYPE: 139,
                SP_ID: 0,
                ABS_EFF_DATE: "2025-09-26 16:28:29",
                OFFER_TYPE: "3",
                OFFER_NAME: "Data Service",
                OFFER_ID: 73,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "c8c8e933-edec-4c7b-8300-4dce09290fdc",
                OLD_EFF_DATE: "2025-09-26 16:28:29",
                OFFER_INST_ID: 121308012,
                ORDER_ITEM_ID: 121178278,
              },
              {
                TIMER_EVENT_ID: 1921,
                DP_OFFER_ORDER_ATTR: [
                  {
                    ATTR_VALUE: "1",
                    OFFER_ID: 213,
                    ATTR_ID: 624,
                    OPERATION_TYPE: "X",
                  },
                  {
                    ATTR_VALUE: "1",
                    OFFER_ID: 213,
                    ATTR_ID: 400003,
                    OPERATION_TYPE: "X",
                  },
                  {
                    ATTR_VALUE: "0",
                    OFFER_ID: 213,
                    ATTR_ID: 400004,
                    OPERATION_TYPE: "X",
                  },
                ],
                OLD_RESERVE_DATE: "2025-11-26 17:02:06",
                OFFER_ID: 213,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "d1130842-9fbb-4e64-a1d2-d1af20b05e40",
                RESERVE_DATE: "2025-11-26 17:02:06",
                REL_EXP_UNIT: "D",
                REL_EXP_OFFSET: 3,
                DUPLICATE_FLAG: "B",
              },
              {
                TIMER_EVENT_ID: 1941,
                OLD_RESERVE_DATE: "2025-12-03 17:02:06",
                OFFER_ID: 1001,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "da0209a5-9268-4154-a18c-bad1737b00c2",
                RESERVE_DATE: "2025-12-03 17:02:06",
                REL_EXP_UNIT: "",
                DUPLICATE_FLAG: "",
              },
              {
                TIMER_EVENT_ID: 1942,
                DP_OFFER_ORDER_ATTR: [
                  {
                    ATTR_VALUE: "1",
                    OFFER_ID: 213,
                    ATTR_ID: 624,
                    OPERATION_TYPE: "X",
                  },
                  {
                    ATTR_VALUE: "1",
                    OFFER_ID: 213,
                    ATTR_ID: 400003,
                    OPERATION_TYPE: "X",
                  },
                  {
                    ATTR_VALUE: "0",
                    OFFER_ID: 213,
                    ATTR_ID: 400004,
                    OPERATION_TYPE: "X",
                  },
                ],
                OLD_RESERVE_DATE: "2025-12-03 17:02:06",
                OFFER_ID: 213,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "45938d4e-78d4-460e-a999-9da536942c7e",
                RESERVE_DATE: "2025-12-03 17:02:06",
                REL_EXP_UNIT: "D",
                REL_EXP_OFFSET: 3,
                DUPLICATE_FLAG: "B",
              },
            ],
            ACCT: {
              PAYMENT_METHOD_ID: 1,
              CUST_ID: 120265000,
              ROUTING_ID: 1,
              ACCT_ID: 120255000,
              STATE: "A",
              BILLING_CYCLE_TYPE_ID: 1,
              DELIVER_METHOD: "",
              PAYMENT_TYPE: "A",
              DEFAULT_FLAG: "N",
              PARTY_TYPE: "A",
              ACCT_NBR: "930255000",
              POSTPAID: "N",
              PARTY_CODE: "1",
            },
            SUBS_PLAN_NAME: "SC_1000_Prepaid_Reguler",
            CUST_ORDER_ID: 121219849,
            OFFER_ID: 4,
            CONTACT_CHANNEL_ID: 1,
            IS_CHECK_OWE_CHARGE: true,
            SUBS_EVENT_ID: 189,
            ORDER_NBR: "2025120321178278",
            ACCT_ID: 120255000,
            IS_RESERVE: true,
            ORDER_TYPE: "B",
            OPERATION_TYPE: "A",
            SUBS_PLAN_ID: 360,
            CUST_ID: 120265000,
            SP_ID: 0,
            STATE_DATE: "2025-12-03 23:47:43",
            ORDER_STATE: "I",
            POS_SALE_MODE: 1,
            PREFIX: "670",
            IS_SAVED: true,
            POSTPAID: "N",
            PROD_STATE: "A",
            BLOCK_REASON: "00000000000000",
            SUBS_ID: 121308008,
            BESP_ADDRESS: "2025-12-05 17:02:06",
            OFFER_NAME: "Telkomcel Prepaid Channel",
            ACC_NBR: "73007362",
            ORDER_ITEM_ID: 121178278,
            CUST_NAME: "Development Test",
          },
        ],
        CUST: {
          CUST_ID: 120265000,
          ROUTING_ID: 1,
          CUST_TYPE: "A",
          CUST_CODE: "1120265000",
          CERT_ID: 120011000,
          CUST_NAME: "Development Test",
        },
        SUBS_EVENT_ID: 189,
        CUST_CONTACT: {
          CUST_ID: 120265000,
          CREATED_DATE: "2025-12-03 23:47:43",
          SP_ID: 0,
          PARTY_TYPE: "A",
          CUST_CONTACT_ID: 187456649,
          CONTACT_TYPE: "A",
          CONTACT_CHANNEL_ID: 1,
          RELA_ID: 121219849,
          CONTACT_EVENT_ID: "A",
          PARTY_CODE: "1",
        },
        PARTY_TYPE: "A",
        SEND_PROVISIONING_FLAG: "Y",
        CUST_ORDER_NBR: "121219849",
        CREDIT_LIMIT_MODE: "0",
        A_PARTY_TYPE: "D",
        STAFF_INFO: { AREA_ID: 1, ORG_ID: 1, STAFF_ID: 1, STAFF_JOB_ID: 1 },
        PARTY_CODE: "1",
      },
      valueType: "VI",
    },
  ],
  dsi: {},
  errors: [],
  hints: [],
  rollbackList: [],
};

const mockselecting = {
  commonDataId: "lweHZC6K9ARc9gT1aqL80625EOFXvtnP",
  boId: null,
  sysEvent: null,
  templateId: null,
  dataChangeList: [
    {
      event: null,
      boId: null,
      boInstId: null,
      locationItemId: null,
      boItemId: null,
      boAccessName: "dpOfferOrder",
      boItemAccessName: "offerSeq",
      oldValue: null,
      value: {
        offerId: "218",
        offerName: "Extend me 1 Month",
        offerCode: "EM1M",
        offerType: "4",
        servType: "",
        offerGroupId: "25",
        offerGroupName: "",
        effType: "B",
        relExpOffset: "0",
        relExpUnit: "H",
        relAgmOffset: "",
        relAgmUnit: "",
        duplicateFlag: "C",
        mrcListPrice: "0",
        mrcSalesPrice: "0",
        otcListPrice: "0",
        otcSalesPrice: "0",
        offerSeq: "SjCzTALiX0S4fGGtYIXmcs9HzH4cDJ2x",
        operationType: "A",
        spId: 0,
      },
      orderItemId: 121178278,
      arrayKeyField: null,
      operationType: "A",
      parentKeyValue: null,
      bo: true,
    },
  ],
  requestDsi: false,
  refreshDirty: true,
  action: "BO_CHANGE",
  bfmKey: "lweHZC6K9ARc9gT1aqL80625EOFXvtnP",
};

const mockpayload = {
  custOrderDto: {
    custOrderId: 121119565,
    aPartyCode: "1585890",
    aPartyType: "D",
    partyType: "D",
    partyCode: "1585890",
    certType: null,
    custId: 1585890,
    acceptDate: "2024-01-12T03:02:05",
    createdDate: "2024-01-12T03:02:05",
    contact: null,
    confirmDate: "2024-01-12T03:02:05",
    spId: 0,
    discountCharge: null,
    promotionPlanId: null,
    orderState: "C",
    stateDate: "2024-01-12T03:02:05",
    dispatchOrderId: null,
    custOrderNbr: "121119565",

    custContact: {},
    orderItemList: [
      {
        orderItemId: 10001,
        custOrderId: 121119565,
        subsId: 360,
        orderState: "C",
        stateDate: "2024-01-12T03:02:05",
        operationType: "ADD",
        offerId: 9999,
        orderReasonId: 1,
        orderReason: "New Order",
        comments: "Initial order item",

        now: "2024-01-12T03:02:05",

        prodModified: false,
        subsModified: false,
        isReserve: false,
        isCheckOweCharge: true,
        isSaved: true,

        spId: 1,
        priority: 1,

        partyType: "D",
        partyCode: "1585890",

        acctId: 1004203,
        custId: 1585890,

        subsBaseOrder: {
          subsId: 360,
          prodId: 101,
          servType: 1,
          effectiveDate: "2024-01-12T03:02:05",
          expireDate: null,
        },

        resOrderList: [
          {
            resId: 1,
            resType: "SIM",
            effDate: "2024-01-12T03:02:05",
            expDate: null,
            status: "ACTIVE",
          },
        ],

        orderItemAttrList: [
          {
            attrId: 2001,
            attrName: "LANG",
            attrValue: "EN",
          },
        ],

        indepProdOrderAttrList: [],
        dpOfferOrderList: [],
        subsBindOrderList: [],
        custProfOrderList: [],
        homeZoneOrderList: [],
        homeCellOrderList: [],
        fellowNbrOrderList: [],
        creditLimitOrderList: [],
        simCardInfoOrderList: [],
        balShareOrderList: [],
        goodsOrderList: [],
        batchResOrderList: [],
        orderRelaList: [],
        individualLifecycleOrderList: [],
        creditBalanceOrderList: [],

        cust: {},
        subs: {},
        acct: {},
        custProf: {},
        acctProf: {},

        deliveryInfoList: [],
        archiveInfo: {},

        refAttr: null,
        prefix: null,
        accNbr: null,
        orderType: "NORMAL",
      },
    ],

    contactChannelId: 1,
    channelType: 1,

    reSubsOrderInstList: [],
    reCcInstDataList: [],

    eventPaymentData: {},
    staffInfo: {},
    acctList: [],
    timerEventList: [],

    subsId: 360,
    acctId: 1004203,
    posSaleMode: null,
    injectType: null,
    isCarryHandset: "N",
    isNeedQryFee: "Y",
    isNeedPayment: "N",
    callTransfer: "N",

    currentOrderItem: {},
    cust: {},

    deductAcctId: 120254131,

    sendProvisioningFlag: "Y",
    isNeedSave: "Y",
    routingId: 1,
    creditLimitMode: null,
  },

  listOrderData: [
    {
      subsId: 360,
      subsEventId: null,
      custId: 1585890,
      acctId: 1004203,

      contactEventId: null,
      contactChannelId: 1,
      contactType: null,
      channelType: 1,

      businessChannelId: null,
      businessChannelType: null,

      partyType: "D",
      partyCode: "1585890",

      creditLimit: null,

      now: "2024-01-12T03:02:05",
      completedDate: "2024-01-12T03:02:05",
      billingStartDate: "2024-01-12T03:02:05",
      bespDate: "2024-01-12T03:02:05",

      oldPpsPwd: null,
      refAttr: null,
      servType: null,

      comments: null,
      spId: 0,
      transactionId: null,

      orderItemId: null,
      orderReasonId: null,
      orderReason: null,

      isNeedQryFee: "Y",
      deductAcctId: 120254131,

      cust: {},
      acct: {},
      subs: {},

      resList: [],
      indepProdAttrList: [],
      fellowNbrList: [],
      dpOfferList: [],

      simCardInfo: {},
      reason: {},
      baseInfo: {},

      homeZoneList: [],
      homeCellList: [],
      subsBindList: [],

      custAcct: {},
      orderAttrList: [],
      balShareList: [],
      custProfList: [],
      creditLimitInfoList: [],
      individualLifecycleInfoList: [],
      creditBalanceInfoList: [],
      goodsList: [],

      bcMember: {},

      routingId: 1,
      isCheckOweCharge: true,
      callTransfer: "N",
      isCalRatingFee: null,
      sendProvisioningFlag: "Y",
      isNeedSave: "Y",

      feeSubsId: null,
      feeAcctId: null,

      custOrderId: 121119565,
      isReserve: false,

      orderRelationList: [],
    },
  ],
};

const mockShop = {
  boAccessName: "custOrder",
  commonDataId: "FGl1I34OM9btrKLwJEuJ34ry4ooIBCxs",
  dirtyList: [
    {
      action: "OVERRIDE",
      bo: false,
      boAccessName: "custOrder",
      filters: {},
      flushed: false,
      isRoot: "Y",
      location: {
        accessNamePath: "/",
        array: false,
        bo: true,
        dataType: "BO",
        includeObjectId: "2f20e016-f047-4677-abe6-7df4b370f121",
        itemAccessName: "custOrder",
        itemType: "VI",
        parentArray: false,
      },
      value: {
        SERV_TYPE: "15",
        CUST_ID: 120265000,
        CREATED_DATE: "2026-01-14 16:54:21",
        SP_ID: 0,
        ACCEPT_DATE: "2026-01-14 16:54:21",
        ACCT: [
          {
            PAYMENT_METHOD_ID: 1,
            CUST_ID: 120265000,
            ROUTING_ID: 1,
            ACCT_ID: 120255000,
            STATE: "A",
            BILLING_CYCLE_TYPE_ID: 1,
            PAYMENT_TYPE: "A",
            DEFAULT_FLAG: "N",
            PARTY_TYPE: "A",
            ACCT_NBR: "930255000",
            POSTPAID: "N",
            PARTY_CODE: "1",
          },
        ],
        CUST_ORDER_ID: 121220152,
        ROUTING_ID: 1,
        OFFER_ID: "4",
        POS_SALE_MODE: 1,
        CONTACT_CHANNEL_ID: 1,
        A_PARTY_CODE: "120265000",
        ORDER_ITEM: [
          {
            SERV_TYPE: 15,
            DP_OFFER_ORDER: [
              {
                SP_ID: 0,
                OFFER_TYPE: "3",
                EFF_TYPE: "B",
                OFFER_GROUP_ID: 1,
                OFFER_NAME: "Incoming SMS",
                OFFER_ID: 74,
                OPERATION_TYPE: "A",
                OFFER_SEQ: "4895439f-ccc6-4f9d-83a8-faaac4da3d8e",
                ORDER_ITEM_ID: 121179148,
              },
              {
                SP_ID: 0,
                OFFER_TYPE: "3",
                EFF_TYPE: "B",
                OFFER_GROUP_ID: 1,
                OFFER_NAME: "Outgoing SMS",
                OFFER_ID: 75,
                OPERATION_TYPE: "A",
                OFFER_SEQ: "5daf5652-8fd3-49e7-b718-1d26131c4216",
                ORDER_ITEM_ID: 121179148,
              },
              {
                SP_ID: 0,
                OFFER_TYPE: "3",
                EFF_TYPE: "B",
                OFFER_GROUP_ID: 1,
                OFFER_NAME: "Voice Service",
                OFFER_ID: 72,
                OPERATION_TYPE: "A",
                OFFER_SEQ: "15d421ce-cdd0-4cec-a7a2-1a6afb78952b",
                ORDER_ITEM_ID: 121179148,
              },
              {
                SP_ID: 0,
                OFFER_TYPE: "3",
                EFF_TYPE: "B",
                OFFER_GROUP_ID: 1,
                OFFER_NAME: "Data Service",
                OFFER_ID: 73,
                OPERATION_TYPE: "A",
                OFFER_SEQ: "be117d38-2652-4ffd-9b7c-e6417fabc757",
                ORDER_ITEM_ID: 121179148,
              },
              {
                DP_OFFER_ORDER_ATTR: [
                  {
                    ATTR_VALUE: "1",
                    ATTR_NAME: "exp type precision second",
                    ATTR_ID: 624,
                    OPERATION_TYPE: "A",
                    VALUE_MARK: "precision to second",
                  },
                ],
                SP_ID: 0,
                OFFER_TYPE: "4",
                EFF_TYPE: "B",
                OFFER_GROUP_ID: 26,
                OFFER_NAME: "Prepaid_Reguler_DPP",
                OFFER_ID: 79,
                OPERATION_TYPE: "A",
                OFFER_SEQ: "a9da8850-40c5-4fa8-90cd-700fb4c89303",
                ORDER_ITEM_ID: 121179148,
              },
            ],
            ACCT: {
              PAYMENT_METHOD_ID: 1,
              CUST_ID: 120265000,
              ROUTING_ID: 1,
              ACCT_ID: 120255000,
              STATE: "A",
              BILLING_CYCLE_TYPE_ID: 1,
              PAYMENT_TYPE: "A",
              DEFAULT_FLAG: "N",
              PARTY_TYPE: "A",
              ACCT_NBR: "930255000",
              POSTPAID: "N",
              PARTY_CODE: "1",
            },
            SUBS_PLAN_NAME: "SC_1000_Prepaid_Reguler",
            CUST_ORDER_ID: 121220152,
            OFFER_ID: 4,
            CONTACT_CHANNEL_ID: 1,
            INDEP_PROD_ORDER_ATTR: [
              {
                ATTR_VALUE: "0",
                SP_ID: 0,
                ATTR_ID: 400001,
                ORDER_ITEM_ID: 121179148,
                OPERATION_TYPE: "A",
              },
            ],
            IS_CHECK_OWE_CHARGE: true,
            SUBS_EVENT_ID: 1,
            ORDER_NBR: "2026011421179148",
            ACCT_ID: 120255000,
            IS_RESERVE: false,
            ORDER_TYPE: "B",
            OPERATION_TYPE: "A",
            SUBS_PLAN_ID: 360,
            CUST_ID: 120265000,
            SP_ID: 0,
            STATE_DATE: "2026-01-14 16:54:21",
            ORDER_STATE: "I",
            POS_SALE_MODE: 1,
            IS_SAVED: true,
            POSTPAID: "N",
            SUBS_BASE_ORDER: {
              SERV_TYPE: 15,
              CUST_ID: 120265000,
              ORG_ID: 1,
              USER_ID: 120265000,
              SUBS_PLAN_NAME: "SC_1000_Prepaid_Reguler",
              AREA_NAME: "Timor-Leste",
              DEF_LANG_ID: 2,
              POSTPAID: "N",
              AREA_ID: 1,
              DEF_LANG_NAME: "Tetun",
              INDEP_PROD_SPEC_ID: 4,
              ACCT_ID: 120255000,
              USER_NAME: "Development Test",
              OPERATION_TYPE: "A",
              SUBS_PLAN_ID: 360,
              ORDER_ITEM_ID: 121179148,
              ACCT_NBR: "930255000",
              CUST_NAME: "Development Test",
            },
            SUBS_ID: 121310145,
            OFFER_NAME: "Telkomcel Prepaid Channel",
            ORDER_ITEM_ID: 121179148,
            CUST_NAME: "Development Test",
          },
        ],
        CUST: {
          CUST_ID: 120265000,
          ROUTING_ID: 1,
          CUST_TYPE: "A",
          CUST_CODE: "1120265000",
          CERT_ID: 120011000,
          CUST_NAME: "Development Test",
        },
        SUBS_EVENT_ID: "1",
        CUST_CONTACT: {
          CUST_ID: 120265000,
          CREATED_DATE: "2026-01-14 16:54:21",
          SP_ID: 0,
          PARTY_TYPE: "A",
          CUST_CONTACT_ID: 187456952,
          CONTACT_TYPE: "A",
          CONTACT_CHANNEL_ID: 1,
          RELA_ID: 121220152,
          CONTACT_EVENT_ID: "A",
          PARTY_CODE: "1",
        },
        PARTY_TYPE: "A",
        SEND_PROVISIONING_FLAG: "Y",
        CUST_ORDER_NBR: "121220152",
        CREDIT_LIMIT_MODE: "0",
        A_PARTY_TYPE: "D",
        STAFF_INFO: { AREA_ID: 1, ORG_ID: 1, STAFF_ID: 1, STAFF_JOB_ID: 1 },
        PARTY_CODE: "1",
      },
      valueType: "VI",
    },
  ],
  dsi: {},
  errors: [],
  hints: [],
  rollbackList: [],
  wizardPage: {
    accessName:
      "com.ztesoft.zsmart.bss.fiji.cc.orderentry.offer.shoppingcart.subscription.SubscriptionDetail",
    accessPath:
      "fiji/customercare/sharepage/flowpage/orderentry/SubscriptionDetailPage.swf",
    canBackward: false,
    canForward: true,
    code: "SubscriptionDetail",
    id: "SubscriptionDetail",
    properties: {},
  },
};

const mockModSubsStartOrder = {
  boAccessName: "custOrder",
  commonDataId: "7idIs3HOTtYQvO5JCHpik2GgJ9TPZM73",
  dirtyList: [
    {
      action: "OVERRIDE",
      bo: false,
      boAccessName: "custOrder",
      filters: {},
      flushed: false,
      isRoot: "Y",
      location: {
        accessNamePath: "/",
        array: false,
        bo: true,
        dataType: "BO",
        includeObjectId: "2f20e016-f047-4677-abe6-7df4b370f121",
        itemAccessName: "custOrder",
        itemType: "VI",
        parentArray: false,
      },
      value: {
        SERV_TYPE: "15",
        CUST_ID: 120265000,
        CREATED_DATE: "2026-01-15 16:09:22",
        SP_ID: 0,
        ACCEPT_DATE: "2026-01-15 16:09:22",
        CUST_ORDER_ID: 121220157,
        ROUTING_ID: 1,
        OFFER_ID: "4",
        POS_SALE_MODE: 1,
        CONTACT_CHANNEL_ID: 1,
        A_PARTY_CODE: "120265000",
        ORDER_ITEM: [
          {
            SERV_TYPE: 15,
            DP_OFFER_ORDER: [
              {
                SERV_TYPE: 386,
                SP_ID: 0,
                ABS_EFF_DATE: "2025-09-26 16:28:29",
                OFFER_TYPE: "3",
                OFFER_NAME: "Incoming SMS",
                OFFER_ID: 74,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "eda27fe3-e960-48b4-8b1f-be9b2e086cea",
                OLD_EFF_DATE: "2025-09-26 16:28:29",
                OFFER_INST_ID: 121308009,
                ORDER_ITEM_ID: 121179156,
              },
              {
                SERV_TYPE: 385,
                SP_ID: 0,
                ABS_EFF_DATE: "2025-09-26 16:28:29",
                OFFER_TYPE: "3",
                OFFER_NAME: "Outgoing SMS",
                OFFER_ID: 75,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "1e9e06c4-8bac-4c3d-b225-059456648388",
                OLD_EFF_DATE: "2025-09-26 16:28:29",
                OFFER_INST_ID: 121308010,
                ORDER_ITEM_ID: 121179156,
              },
              {
                SERV_TYPE: 138,
                SP_ID: 0,
                ABS_EFF_DATE: "2025-09-26 16:28:29",
                OFFER_TYPE: "3",
                OFFER_NAME: "Voice Service",
                OFFER_ID: 72,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "5a8fe935-57a7-47d4-9222-8f61b3ab06dc",
                OLD_EFF_DATE: "2025-09-26 16:28:29",
                OFFER_INST_ID: 121308011,
                ORDER_ITEM_ID: 121179156,
              },
              {
                SERV_TYPE: 139,
                SP_ID: 0,
                ABS_EFF_DATE: "2025-09-26 16:28:29",
                OFFER_TYPE: "3",
                OFFER_NAME: "Data Service",
                OFFER_ID: 73,
                OPERATION_TYPE: "X",
                OFFER_SEQ: "49d91b9f-73d1-4ef6-876c-07e630a9de72",
                OLD_EFF_DATE: "2025-09-26 16:28:29",
                OFFER_INST_ID: 121308012,
                ORDER_ITEM_ID: 121179156,
              },
            ],
            ACCT: {
              PAYMENT_METHOD_ID: 1,
              CUST_ID: 120265000,
              ROUTING_ID: 1,
              ACCT_ID: 120255000,
              STATE: "A",
              BILLING_CYCLE_TYPE_ID: 1,
              DELIVER_METHOD: "",
              PAYMENT_TYPE: "A",
              DEFAULT_FLAG: "N",
              PARTY_TYPE: "A",
              ACCT_NBR: "930255000",
              POSTPAID: "N",
              PARTY_CODE: "1",
            },
            SUBS_PLAN_NAME: "SC_1000_Prepaid_Reguler",
            CUST_ORDER_ID: 121220157,
            OFFER_ID: 4,
            CONTACT_CHANNEL_ID: 1,
            IS_CHECK_OWE_CHARGE: true,
            SUBS_EVENT_ID: 189,
            ORDER_NBR: "2026011521179156",
            ACCT_ID: 120255000,
            IS_RESERVE: false,
            ORDER_TYPE: "B",
            OPERATION_TYPE: "A",
            SUBS_PLAN_ID: 360,
            CUST_ID: 120265000,
            SP_ID: 0,
            STATE_DATE: "2026-01-15 16:09:22",
            ORDER_STATE: "I",
            POS_SALE_MODE: 1,
            PREFIX: "670",
            IS_SAVED: true,
            POSTPAID: "N",
            PROD_STATE: "D",
            BLOCK_REASON: "00000100000000",
            SUBS_ID: 121308008,
            OFFER_NAME: "Telkomcel Prepaid Channel",
            ACC_NBR: "73007362",
            ORDER_ITEM_ID: 121179156,
            CUST_NAME: "Development Test",
          },
        ],
        CUST: {
          CUST_ID: 120265000,
          ROUTING_ID: 1,
          CUST_TYPE: "A",
          CUST_CODE: "1120265000",
          CERT_ID: 120011000,
          CUST_NAME: "Development Test",
        },
        SUBS_EVENT_ID: 189,
        CUST_CONTACT: {
          CUST_ID: 120265000,
          CREATED_DATE: "2026-01-15 16:09:22",
          SP_ID: 0,
          PARTY_TYPE: "A",
          CUST_CONTACT_ID: 187456957,
          CONTACT_TYPE: "A",
          CONTACT_CHANNEL_ID: 1,
          RELA_ID: 121220157,
          CONTACT_EVENT_ID: "A",
          PARTY_CODE: "1",
        },
        PARTY_TYPE: "A",
        SEND_PROVISIONING_FLAG: "Y",
        CUST_ORDER_NBR: "121220157",
        CREDIT_LIMIT_MODE: "0",
        A_PARTY_TYPE: "D",
        STAFF_INFO: { AREA_ID: 1, ORG_ID: 1, STAFF_ID: 1, STAFF_JOB_ID: 1 },
        PARTY_CODE: "1",
      },
      valueType: "VI",
    },
  ],
  dsi: {},
  errors: [],
  hints: [],
  rollbackList: [],
  wizardPage: {
    accessName:
      "com.ztesoft.zsmart.bss.fiji.cc.orderentry.products.view.BusinessChange",
    accessPath:
      "fiji/customercare/sharepage/flowpage/orderentry/BusinessChangePage.swf",
    canBackward: false,
    canForward: true,
    code: "BusinessChange",
    id: "BusinessChange",
    properties: {},
  },
};

export const datasStep3: queryTempTable[] = [
  {
    rownum: "1",
    rowno: "1",
    iccid: "8863017294619273",
    simCardId: 123,
    prefix: "670",
    accNbr: "7329173012",
    accNbrId: 12,
  },
  {
    rownum: "2",
    rowno: "2",
    iccid: "987692717721233",
    simCardId: 124,
    prefix: "670",
    accNbr: "7328367013",
    accNbrId: 13,
  },
  {
    rownum: "3",
    rowno: "2",
    iccid: "10237821983173123",
    simCardId: 125,
    prefix: "670",
    accNbr: "7326712012",
    accNbrId: 14,
  },
];
