import { AccountInfo } from "./interfaces";

export const mockAcc: AccountInfo[] = [
  {
    defLangId: "",
    noSubsFlag: "",
    rutName: "",
    needUpload: "",
    allowModStateDate: "",
    custBillDeliveryInfoId: 12601,
    industryId: "",
    billFlag: "Y",
    deliverMethod: "",
    creditLimit: "",
    custBillDelivery: {
      updateDate: "2025/09/26 16:24:58",
      ccEmail: "",
      detailInfo: "",
      stdAddr: "",
      partyCodeName: "",
      partyType: "A",
      spId: "0",
      zipcode: "",
      custBillDeliveryInfoId: 12601,
      createdDate: "2025/09/26 16:24:58",
      smsNbr: "",
      partyCode: "1",
      custId: "120265000",
      state: "A",
      faxNbr: "",
      email: "",
      fileType: "",
      stdAddrId: "",
    },
    balId: "",
    state: "A",
    createPartyType: "",
    bankAcctIssueDate: "",
    isHybridOffer: "",
    defaultFlag: "N",
    billFormatName: "",
    billingCycleTypeName: "PREPAID",
    acctId: 120255000,
    fingerMark: "",
    payerNumber: "",
    paymentMethodName: "Cash",
    bankId: "",
    billAddress: "",
    operationType: "",
    billingCycleType: "",
    bankAcctNbr: "",
    stdAddrId: "",
    updateDate: "2025/09/26 16:24:58",
    rutNbr: "",
    routingId: "1",
    postpaid: "N",
    bankName: "",
    partyType: "",
    paymentComments: "",
    paymentType: "A",
    isLock: "",
    bankAcctExpDate: "",
    paymentMethodId: 1,
    mandateId: "",
    custId: "120265000",
    billFormatId: "",
    bankAcctName: "",
    createPartyCode: "",
    paymentTypeName: "Automatic payment",
    deliverMethodName: "",
    acctAttrValueList: "",
    bankCardType: "",
    acctName: "",
    custName: "Development Test",
    spId: "",
    parentAcctId: "",
    billingCycleTypeId: 1,
    createdDate: "2025/09/26 16:24:58",
    billCurrency: undefined,
    partyCode: "",
    stateDate: "2025/09/26 16:24:58",
    acctNbr: "930255000",
  },
  {
    defLangId: "",
    noSubsFlag: "",
    rutName: "",
    needUpload: "",
    allowModStateDate: "",
    custBillDeliveryInfoId: 12601,
    industryId: "",
    billFlag: "Y",
    deliverMethod: "",
    creditLimit: "",
    custBillDelivery: {
      updateDate: "2025/09/26 16:24:58",
      ccEmail: "",
      detailInfo: "",
      stdAddr: "",
      partyCodeName: "",
      partyType: "A",
      spId: "0",
      zipcode: "",
      custBillDeliveryInfoId: 12601,
      createdDate: "2025/09/26 16:24:58",
      smsNbr: "",
      partyCode: "1",
      custId: "120265000",
      state: "A",
      faxNbr: "",
      email: "",
      fileType: "",
      stdAddrId: "",
    },
    balId: "",
    state: "A",
    createPartyType: "",
    bankAcctIssueDate: "",
    isHybridOffer: "",
    defaultFlag: "N",
    billFormatName: "",
    billingCycleTypeName: "PREPAID",
    acctId: 99999999,
    fingerMark: "",
    payerNumber: "",
    paymentMethodName: "Cash",
    bankId: "",
    billAddress: "",
    operationType: "",
    billingCycleType: "",
    bankAcctNbr: "",
    stdAddrId: "",
    updateDate: "2025/09/26 16:24:58",
    rutNbr: "",
    routingId: "1",
    postpaid: "N",
    bankName: "",
    partyType: "",
    paymentComments: "",
    paymentType: "X",
    isLock: "",
    bankAcctExpDate: "",
    paymentMethodId: 1,
    mandateId: "",
    custId: "120265000",
    billFormatId: "",
    bankAcctName: "",
    createPartyCode: "",
    paymentTypeName: "Manual payment",
    deliverMethodName: "",
    acctAttrValueList: "",
    bankCardType: "",
    acctName: "",
    custName: "Development Test",
    spId: "",
    parentAcctId: "",
    billingCycleTypeId: 1,
    createdDate: "2025/09/26 16:24:58",
    billCurrency: undefined,
    partyCode: "",
    stateDate: "2025/09/26 16:24:58",
    acctNbr: "930255000",
  },
];
